async function createKtxModule(moduleArg={}){var moduleRtn;var f=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope;f.Ih=function(){f.ktxTexture=f.Lh;f.ErrorCode=f.Dh;f.TranscodeTarget=f.Oh;f.TranscodeFlags=f.Nh};var ca="./this.program",da=import.meta.url,ea="",fa,ha;
if(aa||ba){try{ea=(new URL(".",da)).href}catch{}ba&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});fa=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ia=console.log.bind(console),g=console.error.bind(console),ja,ka=!1,la,ma,na,n,r,t,u,w,x,y,oa,pa,qa,ra=!1;
function sa(){var a=ta.buffer;f.HEAP8=n=new Int8Array(a);t=new Int16Array(a);f.HEAPU8=r=new Uint8Array(a);u=new Uint16Array(a);w=new Int32Array(a);x=new Uint32Array(a);y=new Float32Array(a);oa=new Float64Array(a);pa=new BigInt64Array(a);qa=new BigUint64Array(a)}function ua(a){f.onAbort?.(a);a="Aborted("+a+")";g(a);ka=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");na?.(a);throw a;}var va;
async function wa(a){if(!ja)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==va&&ja)a=new Uint8Array(ja);else if(ha)a=ha(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){g(`failed to asynchronously prepare wasm: ${d}`),ua(d)}}
async function ya(a){var b=va;if(!ja)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){g(`wasm streaming compile failed: ${d}`),g("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Aa=a=>{for(;0<a.length;)a.shift()(f)},Ba=[],Ca=[],Da=()=>{var a=f.preRun.shift();Ca.push(a)},Ea=!0;class Fa{constructor(a){this.rf=a-24}}
var Ga=0,Ha=0,Ia=new TextDecoder,Ja=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},A=(a,b,c)=>(a>>>=0)?Ia.decode(r.subarray(a>>>0,Ja(r,a,b,c)>>>0)):"",Ka={},La=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Ma(a){return this.uf(x[a>>>2>>>0])}
var B={},G={},Na={},Oa=class extends Error{constructor(a){super(a);this.name="InternalError"}},I=(a,b,c)=>{function d(l){l=c(l);if(l.length!==a.length)throw new Oa("Mismatched type converter count");for(var m=0;m<a.length;++m)H(a[m],l[m])}a.forEach(l=>Na[l]=b);var e=Array(b.length),h=[],k=0;b.forEach((l,m)=>{G.hasOwnProperty(l)?e[m]=G[l]:(h.push(l),B.hasOwnProperty(l)||(B[l]=[]),B[l].push(()=>{e[m]=G[l];++k;k===h.length&&d(e)}))});0===h.length&&d(e)},J=a=>{a>>>=0;for(var b="";;){var c=r[a++>>>0];
if(!c)return b;b+=String.fromCharCode(c)}},L=class extends Error{constructor(a){super(a);this.name="BindingError"}},Pa=a=>{throw new L(a);};function Qa(a,b,c={}){var d=b.name;if(!a)throw new L(`type "${d}" must have a positive integer typeid pointer`);if(G.hasOwnProperty(a)){if(c.mh)return;throw new L(`Cannot register type '${d}' twice`);}G[a]=b;delete Na[a];B.hasOwnProperty(a)&&(b=B[a],delete B[a],b.forEach(e=>e()))}function H(a,b,c={}){return Qa(a,b,c)}
var Ra=(a,b,c)=>{switch(b){case 1:return c?d=>n[d>>>0]:d=>r[d>>>0];case 2:return c?d=>t[d>>>1>>>0]:d=>u[d>>>1>>>0];case 4:return c?d=>w[d>>>2>>>0]:d=>x[d>>>2>>>0];case 8:return c?d=>pa[d>>>3>>>0]:d=>qa[d>>>3>>>0];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Sa=a=>{throw new L(a.pf.vf.sf.name+" instance already deleted");},Ta=!1,Ua=()=>{},Va=a=>{if(!globalThis.FinalizationRegistry)return Va=b=>b,a;Ta=new FinalizationRegistry(b=>{b=b.pf;--b.count.value;0===b.count.value&&(b.zf?
b.Cf.If(b.zf):b.vf.sf.If(b.rf))});Va=b=>{var c=b.pf;c.zf&&Ta.register(b,{pf:c},b);return b};Ua=b=>{Ta.unregister(b)};return Va(a)},Wa=[];function Xa(){}
var Ya=(a,b)=>Object.defineProperty(b,"name",{value:a}),Za={},$a=(a,b,c)=>{if(void 0===a[b].Mf){var d=a[b];a[b]=function(...e){if(!a[b].Mf.hasOwnProperty(e.length))throw new L(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].Mf})!`);return a[b].Mf[e.length].apply(this,e)};a[b].Mf=[];a[b].Mf[d.Zf]=d}},ab=(a,b)=>{if(f.hasOwnProperty(a))throw new L(`Cannot register public name '${a}' twice`);f[a]=b;f[a].Zf=void 0},bb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,
"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function db(a,b,c,d,e,h,k,l){this.name=a;this.constructor=b;this.Of=c;this.If=d;this.Af=e;this.eh=h;this.hg=k;this.Yg=l;this.rh=[]}var eb=(a,b,c)=>{for(;b!==c;){if(!b.hg)throw new L(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.hg(a);b=b.Af}return a},fb=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function gb(a,b){if(null===b){if(this.tg)throw new L(`null is not a valid ${this.name}`);return 0}if(!b.pf)throw new L(`Cannot pass "${fb(b)}" as a ${this.name}`);if(!b.pf.rf)throw new L(`Cannot pass deleted object as a pointer of type ${this.name}`);return eb(b.pf.rf,b.pf.vf.sf,this.sf)}
function hb(a,b){if(null===b){if(this.tg)throw new L(`null is not a valid ${this.name}`);if(this.kg){var c=this.xg();null!==a&&a.push(this.If,c);return c}return 0}if(!b||!b.pf)throw new L(`Cannot pass "${fb(b)}" as a ${this.name}`);if(!b.pf.rf)throw new L(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.jg&&b.pf.vf.jg)throw new L(`Cannot convert argument of type ${b.pf.Cf?b.pf.Cf.name:b.pf.vf.name} to parameter type ${this.name}`);c=eb(b.pf.rf,b.pf.vf.sf,this.sf);if(this.kg){if(void 0===
b.pf.zf)throw new L("Passing raw pointer to smart pointer is illegal");switch(this.xh){case 0:if(b.pf.Cf===this)c=b.pf.zf;else throw new L(`Cannot convert argument of type ${b.pf.Cf?b.pf.Cf.name:b.pf.vf.name} to parameter type ${this.name}`);break;case 1:c=b.pf.zf;break;case 2:if(b.pf.Cf===this)c=b.pf.zf;else{var d=b.clone();c=this.sh(c,M(()=>d["delete"]()));null!==a&&a.push(this.If,c)}break;default:throw new L("Unsupporting sharing policy");}}return c}
function ib(a,b){if(null===b){if(this.tg)throw new L(`null is not a valid ${this.name}`);return 0}if(!b.pf)throw new L(`Cannot pass "${fb(b)}" as a ${this.name}`);if(!b.pf.rf)throw new L(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.pf.vf.jg)throw new L(`Cannot convert argument of type ${b.pf.vf.name} to parameter type ${this.name}`);return eb(b.pf.rf,b.pf.vf.sf,this.sf)}
var jb=(a,b,c)=>{if(b===c)return a;if(void 0===c.Af)return null;a=jb(a,b,c.Af);return null===a?null:c.Yg(a)},kb={},lb=(a,b)=>{if(void 0===b)throw new L("ptr should not be undefined");for(;a.Af;)b=a.hg(b),a=a.Af;return kb[b]},mb=(a,b)=>{if(!b.vf||!b.rf)throw new Oa("makeClassHandle requires ptr and ptrType");if(!!b.Cf!==!!b.zf)throw new Oa("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Va(Object.create(a,{pf:{value:b,writable:!0}}))};
function nb(a,b,c,d,e,h,k,l,m,q,p){this.name=a;this.sf=b;this.tg=c;this.jg=d;this.kg=e;this.qh=h;this.xh=k;this.Lg=l;this.xg=m;this.sh=q;this.If=p;e||void 0!==b.Af?this.wf=hb:(this.wf=d?gb:ib,this.Bf=null)}
var ob=(a,b)=>{if(!f.hasOwnProperty(a))throw new Oa("Replacing nonexistent public symbol");f[a]=b;f[a].Zf=void 0},qb=(a,b,c=[])=>{b=pb.get(b)(...c);return"p"==a[0]?b>>>0:b},rb=(a,b)=>(...c)=>qb(a,b,c),N=(a,b)=>{a=J(a);var c=a.includes("p")?rb(a,b):pb.get(b);if("function"!=typeof c)throw new L(`unknown function pointer with signature ${a}: ${b}`);return c};class sb extends Error{}
var ub=a=>{a=tb(a);var b=J(a);O(a);return b},vb=(a,b)=>{function c(h){e[h]||G[h]||(Na[h]?Na[h].forEach(c):(d.push(h),e[h]=!0))}var d=[],e={};b.forEach(c);throw new sb(`${a}: `+d.map(ub).join([", "]));},wb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(x[b+4*d>>>2>>>0]);return c};function xb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Bf)return!0;return!1}
function yb(a,b,c,d,e,h){var k=b.length;if(2>k)throw new L("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,m=xb(b);c=!b[0].Fg;var q=b[0],p=b[1];d=[a,Pa,d,e,La,q.uf.bind(q),p?.wf.bind(p)];for(e=2;e<k;++e)q=b[e],d.push(q.wf.bind(q));if(!m)for(e=l?1:2;e<b.length;++e)null!==b[e].Bf&&d.push(b[e].Bf);m=xb(b);e=b.length-2;p=[];q=["fn"];l&&q.push("thisWired");for(k=0;k<e;++k)p.push(`arg${k}`),q.push(`arg${k}Wired`);p=p.join(",");q=q.join(",");
p=`return function (${p}) {\n`;m&&(p+="var destructors = [];\n");var v=m?"destructors":"null",z="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");l&&(p+=`var thisWired = toClassParamWire(${v}, this);\n`);for(k=0;k<e;++k){var C=`toArg${k}Wire`;p+=`var arg${k}Wired = ${C}(${v}, arg${k});\n`;z.push(C)}p+=(c||h?"var rv = ":"")+`invoker(${q});\n`;if(m)p+="runDestructors(destructors);\n";else for(k=l?1:2;k<b.length;++k)h=1===k?"thisWired":"arg"+(k-2)+"Wired",
null!==b[k].Bf&&(p+=`${h}_dtor(${h});\n`,z.push(`${h}_dtor`));c&&(p+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(z,p+"}\n"))(...d);return Ya(a,b)}
var zb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Ab=(a,b,c)=>{if(!(a instanceof Object))throw new L(`${c} with invalid "this": ${a}`);if(!(a instanceof b.sf.constructor))throw new L(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.pf.rf)throw new L(`cannot call emscripten binding method ${c} on deleted object`);return eb(a.pf.rf,a.pf.vf.sf,b.sf)},Bb=[],Q=[0,1,,1,null,1,!0,1,!1,1];function Cb(a){a>>>=0;9<a&&0===--Q[a+1]&&(Q[a]=void 0,Bb.push(a))}
var R=a=>{if(!a)throw new L(`Cannot use deleted val. handle = ${a}`);return Q[a]},M=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Bb.pop()||Q.length;Q[b]=a;Q[b+1]=1;return b}},Db={name:"emscripten::val",uf:a=>{var b=R(a);Cb(a);return b},wf:(a,b)=>M(b),Ef:Ma,Bf:null},Eb=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.uf(n[d>>>0])}:function(d){return this.uf(r[d>>>0])};case 2:return c?function(d){return this.uf(t[d>>>1>>>0])}:function(d){return this.uf(u[d>>>
1>>>0])};case 4:return c?function(d){return this.uf(w[d>>>2>>>0])}:function(d){return this.uf(x[d>>>2>>>0])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Fb=(a,b)=>{var c=G[a];if(void 0===c)throw a=`${b} has unknown type ${ub(a)}`,new L(a);return c},Gb=(a,b)=>{switch(b){case 4:return function(c){return this.uf(y[c>>>2>>>0])};case 8:return function(c){return this.uf(oa[c>>>3>>>0])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},S=(a,b,c)=>{var d=r;b>>>=0;
if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var k=a.codePointAt(h);if(127>=k){if(b>=c)break;d[b++>>>0]=k}else if(2047>=k){if(b+1>=c)break;d[b++>>>0]=192|k>>6;d[b++>>>0]=128|k&63}else if(65535>=k){if(b+2>=c)break;d[b++>>>0]=224|k>>12;d[b++>>>0]=128|k>>6&63;d[b++>>>0]=128|k&63}else{if(b+3>=c)break;d[b++>>>0]=240|k>>18;d[b++>>>0]=128|k>>12&63;d[b++>>>0]=128|k>>6&63;d[b++>>>0]=128|k&63;h++}}d[b>>>0]=0;return b-e},Hb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:
2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ib=new TextDecoder("utf-16le"),Jb=(a,b,c)=>{a>>>=1;return Ib.decode(u.subarray(a>>>0,Ja(u,a,b/2,c)>>>0))},Kb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)t[b>>>1>>>0]=a.charCodeAt(e),b+=2;t[b>>>1>>>0]=0;return b-d},Lb=a=>2*a.length,Mb=(a,b,c)=>{var d="";a>>>=2;for(var e=0;!(e>=b/4);e++){var h=x[a+e>>>0];if(!h&&!c)break;d+=String.fromCodePoint(h)}return d},Nb=(a,b,c)=>{b>>>=0;c??=2147483647;
if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var h=a.codePointAt(e);65535<h&&e++;w[b>>>2>>>0]=h;b+=4;if(b+4>c)break}w[b>>>2>>>0]=0;return b-d},Ob=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Pb=0,Qb=[],Rb=a=>{var b=Qb.length;Qb.push(a);return b},Sb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Fb(x[b+4*d>>>2>>>0],`parameter ${d}`);return c},Tb=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(x[b>>>2>>>0]=M(d));return a},Ub={},Vb=a=>{var b=Ub[a];return void 0===
b?J(a):b},Wb={},Xb=a=>{if(!(a instanceof za||"unwind"==a))throw a;},Yb=a=>{la=a;Ea||0<Pb||(f.onExit?.(a),ka=!0);throw new za(a);},$b=a=>{if(!ka)try{if(a(),!(Ea||0<Pb))try{la=a=la,Yb(a)}catch(b){Xb(b)}}catch(b){Xb(b)}},T,ac=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,k)=>b.drawElementsInstancedANGLE(c,d,e,h,k))},bc=a=>{var b=a.getExtension("OES_vertex_array_object");
b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},cc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},dc=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},V={counter:1,Gf:[],mg:{},tf:[],cg:[],Wf:[],Tf:[],yf:[],ig:[],Lf:[],Hh:{},xf:[],Ff:[],fg:[],Qf:[],Vg:5120,Ug:[1,1,2,2,4,4,4,2,3,4,8],Ng:{},Og:{},Rg:4,Sg:0,nf:a=>{V.ug||(V.ug=a)},Vf:a=>{for(var b=V.counter++,c=a.length;c<b;c++)a[c]=null;for(;a[b];)b=V.counter++;return b},Nf:(a,b,c,d)=>{for(var e=0;e<a;e++){var h=T[c](),k=h&&V.Vf(d);h?(h.name=k,d[k]=h):V.nf(1282);w[b+4*e>>>2>>>0]=k}},rg:2097152,Ig:64,lg:a=>32-Math.clz32(0===a?0:a-1),dh:(a,
b)=>{var c=V.lg(V.rg);b.Rf=[];b.qg=[];b.Rf.length=b.qg.length=c+1;b.Yf=[];b.eg=[];b.Yf.length=b.eg.length=c+1;b.Xf=[];b.Xf.length=c+1;for(var d=0;d<=c;++d){b.Xf[d]=null;b.Rf[d]=b.qg[d]=0;var e=V.Ig;b.Yf[d]=[];b.eg[d]=[];var h=b.Yf[d],k=b.eg[d];h.length=k.length=e;for(var l=0;l<e;++l)h[l]=k[l]=null}if(a){b.yh=T.createBuffer();b.Jf.bindBuffer(34963,b.yh);a=V.rg>>1;c=new Uint16Array(a);for(e=d=0;;){c[d++]=e;if(d>=a)break;c[d++]=e+1;if(d>=a)break;c[d++]=e+2;if(d>=a)break;c[d++]=e;if(d>=a)break;c[d++]=
e+2;if(d>=a)break;c[d++]=e+3;if(d>=a)break;e+=4}b.Jf.bufferData(34963,c,35044);b.Jf.bindBuffer(34963,null)}},ih:a=>{a=V.lg(a);var b=V.qf.Yf[a],c=V.qf.Rf[a];V.qf.Rf[a]=V.qf.Rf[a]+1&V.Ig-1;var d=b[c];if(d)return d;d=T.getParameter(34964);b[c]=T.createBuffer();T.bindBuffer(34962,b[c]);T.bufferData(34962,1<<a,35048);T.bindBuffer(34962,d);return b[c]},hh:a=>{a=V.lg(a);var b=V.qf.Xf[a];if(b)return b;b=T.getParameter(34965);V.qf.Xf[a]=T.createBuffer();T.bindBuffer(34963,V.qf.Xf[a]);T.bufferData(34963,1<<
a,35048);T.bindBuffer(34963,b);return V.qf.Xf[a]},ph:()=>{if(V.qf){var a=V.qf.Yf;V.qf.Yf=V.qf.eg;V.qf.eg=a;a=V.qf.Rf;V.qf.Rf=V.qf.qg;V.qf.qg=a;a=V.lg(V.rg);for(var b=0;b<=a;++b)V.qf.Rf[b]=0}},gh:(a,b,c,d)=>{a="";for(var e=0;e<b;++e)a+=A(x[c+4*e>>>2>>>0],d?x[d+4*e>>>2>>>0]:void 0);return a},Cg:(a,b,c,d)=>0<c?d*c:a*V.Ug[b-V.Vg]*d,Ph:[],Kg:a=>{V.Mg=!1;for(var b=0;b<V.qf.vg;++b){var c=V.qf.Kf[b];if(c.Uf&&c.enabled){V.Mg=!0;var d=V.Cg(c.size,c.type,c.stride,a),e=V.ih(d);T.bindBuffer(34962,e);T.bufferSubData(34962,
0,r.subarray(c.rf>>>0,c.rf+d>>>0));c.zg.call(T,b,c.size,c.type,c.wg,c.stride,0)}}},Jg:()=>{V.Mg&&T.bindBuffer(34962,V.Gf[T.$f])},Ah:(a,b)=>{if(f.preinitializedWebGLContext){var c=f.preinitializedWebGLContext;b.Gg=Number(c.getParameter(c.VERSION).match(/^WebGL (\d+).\d+/)[1])}else a.Hg||(a.Hg=a.getContext,a.getContext=function(d,e){e=a.Hg(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null}),c=1<b.Gg?a.getContext("webgl2",b):a.getContext("webgl",b);return c?V.th(c,b):0},th:(a,b)=>{var c=
V.Vf(V.Lf),d={handle:c,attributes:b,version:b.Gg,Jf:a};a.canvas&&(a.canvas.Tg=d);V.Lf[c]=d;("undefined"==typeof b.Zg||b.Zg)&&V.nh(d);d.vg=d.Jf.getParameter(34921);d.Kf=[];for(a=0;a<d.vg;a++)d.Kf[a]={enabled:!1,Uf:!1,size:0,type:0,wg:0,stride:0,rf:0,zg:null};V.dh(!1,d);return c},Eh:a=>{V.qf=V.Lf[a];f.ctx=T=V.qf?.Jf;return!(a&&!T)},getContext:a=>V.Lf[a],Bh:a=>{V.qf===V.Lf[a]&&(V.qf=null);"object"==typeof JSEvents&&JSEvents.Kh(V.Lf[a].Jf.canvas);V.Lf[a]?.Jf.canvas&&(V.Lf[a].Jf.canvas.Tg=void 0);V.Lf[a]=
null},nh:a=>{a||=V.qf;if(!a.oh){a.oh=!0;var b=a.Jf;b.Gh=b.getExtension("WEBGL_multi_draw");b.ah=b.getExtension("EXT_polygon_offset_clamp");b.$g=b.getExtension("EXT_clip_control");b.zh=b.getExtension("WEBGL_polygon_mode");ac(b);bc(b);cc(b);b.Ch=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Fh=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Df=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Df)b.Df=b.getExtension("EXT_disjoint_timer_query");
dc(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}},ec=a=>{T.bindVertexArray(V.ig[a]);a=T.getParameter(34965);T.ag=a?a.name|0:0};function fc(a,b){b>>>=0;for(var c=0;c<a;c++){var d=w[b+4*c>>>2>>>0];T.deleteVertexArray(V.ig[d]);V.ig[d]=null}}var gc=(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},hc=[];function ic(a,b){b>>>=0;for(var c=hc[a],d=0;d<a;d++)c[d]=w[b+4*d>>>2>>>0];T.drawBuffers(c)}
function jc(a,b,c,d){d>>>=0;var e=0;if(!T.ag){var h=V.Cg(1,c,0,b);var k=V.hh(h);T.bindBuffer(34963,k);T.bufferSubData(34963,0,r.subarray(d>>>0,d+h>>>0));if(0<b)for(k=0;k<V.qf.vg;++k)if(h=V.qf.Kf[k],h.Uf&&h.enabled){switch(c){case 5121:e=Uint8Array;break;case 5123:e=Uint16Array;break;case 5125:e=Uint32Array;break;default:V.nf(1282);return}e=(new e(r.buffer,d,b)).reduce((l,m)=>Math.max(l,m))+1;break}d=0}V.Kg(e);T.drawElements(a,b,c,d);V.Jg(b);T.ag||T.bindBuffer(34963,null)}
function kc(a,b,c,d,e){T.drawElementsInstanced(a,b,c,d>>>0,e)}var lc=a=>{switch(a){case 34962:a=34964;break;case 34963:a=34965;break;case 35051:a=35053;break;case 35052:a=35055;break;case 35982:a=35983;break;case 36662:a=36662;break;case 36663:a=36663;break;case 35345:a=35368}return(a=T.getParameter(a))?a.name|0:0},mc=a=>{switch(a){case 34962:case 34963:case 36662:case 36663:case 35051:case 35052:case 35882:case 35982:case 35345:return!0;default:return!1}};
function nc(a,b){V.Nf(a,b>>>0,"createVertexArray",V.ig)}
var oc=(a,b,c,d,e,h,k,l)=>{b=V.tf[b];if(a=T[a](b,c))d=l&&S(a.name,l,d),e&&(w[e>>>2>>>0]=d),h&&(w[h>>>2>>>0]=a.size),k&&(w[k>>>2>>>0]=a.type)},pc=(a,b)=>{x[a>>>2>>>0]=b;x[a+4>>>2>>>0]=(b-x[a>>>2>>>0])/4294967296},qc=()=>{var a=dc(T);return a=a.concat(a.map(b=>"GL_"+b))},rc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&V.nf(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=T.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>V.qf.version){V.nf(1282);
return}d=qc().length;break;case 33307:case 33308:if(2>V.qf.version){V.nf(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=T.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":V.nf(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:V.nf(1280);
return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+4*a>>>2>>>0]=e[a];break;case 2:y[b+4*a>>>2>>>0]=e[a];break;case 4:n[b+a>>>0]=e[a]?1:0}return}try{d=e.name|0}catch(h){V.nf(1280);g(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${h})`);return}}break;default:V.nf(1280);g(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:pc(b,d);break;case 0:w[b>>>2>>>0]=d;break;case 2:y[b>>>2>>>0]=d;break;case 4:n[b>>>0]=d?1:0}}else V.nf(1281)},sc=(a,b,c,d)=>{if(c){b=T.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:V.nf(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{V.nf(1280);return}break;default:V.nf(1280);return}switch(d){case 1:pc(c,a);break;case 0:w[c>>>2>>>0]=a;break;
case 2:y[c>>>2>>>0]=a;break;case 4:n[c>>>0]=a?1:0;break;default:ua("internal emscriptenWebGLGetIndexed() error, bad type: "+d)}}else V.nf(1281)};function tc(a,b,c){if(c>>>=0){a=V.xf[a];b=2>V.qf.version?T.Df.getQueryObjectEXT(a,b):T.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;pc(c,d)}else V.nf(1281)}function uc(a,b,c){if(c>>>=0){a=T.Df.getQueryObjectEXT(V.xf[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>>2>>>0]=d}else V.nf(1281)}
var wc=a=>{var b=Hb(a)+1,c=vc(b);c&&S(a,c,b);return c},xc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),yc=a=>{var b=a.gg,c=a.Qg,d;if(!b){a.gg=b={};a.Pg={};var e=T.getProgramParameter(a,35718);for(d=0;d<e;++d){var h=T.getActiveUniform(a,d);var k=h.name;h=h.size;var l=xc(k);l=0<l?k.slice(0,l):k;var m=a.yg;a.yg+=h;c[l]=[h,m];for(k=0;k<h;++k)b[m]=k,a.Pg[m++]=l}}},W=a=>{var b=T.Xg;if(b){var c=b.gg[a];"number"==typeof c&&(b.gg[a]=c=T.getUniformLocation(b,b.Pg[a]+(0<c?`[${c}]`:"")));return c}V.nf(1282)},zc=(a,
b,c,d)=>{if(c)if(a=V.tf[a],yc(a),a=T.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>>2>>>0]=a;break;case 2:y[c>>>2>>>0]=a}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>>2>>>0]=a[b];break;case 2:y[c+4*b>>>2>>>0]=a[b]}else V.nf(1281)},Ac=(a,b,c,d)=>{if(c)if(V.qf.Kf[a].enabled&&g("glGetVertexAttrib*v on client-side array: not supported, bad data returned"),a=T.getVertexAttrib(a,b),34975==b)w[c>>>2>>>0]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>>
2>>>0]=a;break;case 2:y[c>>>2>>>0]=a;break;case 5:w[c>>>2>>>0]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>>2>>>0]=a[b];break;case 2:y[c+4*b>>>2>>>0]=a[b];break;case 5:w[c+4*b>>>2>>>0]=Math.fround(a[b])}else V.nf(1281)};function Bc(a,b,c){Ac(a,b,c>>>0,0)}
var Cc=a=>(a=V.ig[a])?T.isVertexArray(a):0,Dc=a=>{a-=5120;return 0==a?n:1==a?r:2==a?t:4==a?w:6==a?y:5==a||28922==a||28520==a||30779==a||30782==a?x:u},Ec=(a,b,c,d,e)=>{a=Dc(a);var h=V.Rg;b=d*((V.Sg||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+h-1&-h);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT)>>>0,e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT)>>>0)},X=[],Fc=[],Gc=(a,b)=>{T.vertexAttribDivisor(a,b)},Hc={},Jc=()=>{if(!Ic){var a={USER:"web_user",
LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Hc)void 0===Hc[b]?delete a[b]:a[b]=Hc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ic=c}return Ic},Ic,Kc=[null,[],[]],Oc=(a,b,c,d)=>{var e={string:q=>{var p=0;if(null!==q&&void 0!==q&&0!==q){p=Hb(q)+1;var v=Lc(p);S(q,v,p);p=v}return p},array:q=>{var p=Lc(q.length);n.set(q,p>>>0);return p}};a=f["_"+a];var h=[],k=0;if(d)for(var l=
0;l<d.length;l++){var m=e[c[l]];m?(0===k&&(k=Mc()),h[l]=m(d[l])):h[l]=d[l]}c=a(...h);return c=function(q){0!==k&&Nc(k);return"string"===b?A(q):"boolean"===b?!!q:q}(c)};
(()=>{let a=Xa.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Xa&&c instanceof Xa))return!1;var d=this.pf.vf.sf,e=this.pf.rf;c.pf=c.pf;var h=c.pf.vf.sf;for(c=c.pf.rf;d.Af;)e=d.hg(e),d=d.Af;for(;h.Af;)c=h.hg(c),h=h.Af;return d===h&&e===c},clone:function(){this.pf.rf||Sa(this);if(this.pf.dg)return this.pf.count.value+=1,this;var c=Va,d=Object,e=d.create,h=Object.getPrototypeOf(this),k=this.pf;c=c(e.call(d,h,{pf:{value:{count:k.count,bg:k.bg,dg:k.dg,rf:k.rf,vf:k.vf,zf:k.zf,Cf:k.Cf}}}));
c.pf.count.value+=1;c.pf.bg=!1;return c},["delete"](){this.pf.rf||Sa(this);if(this.pf.bg&&!this.pf.dg)throw new L("Object already scheduled for deletion");Ua(this);var c=this.pf;--c.count.value;0===c.count.value&&(c.zf?c.Cf.If(c.zf):c.vf.sf.If(c.rf));this.pf.dg||(this.pf.zf=void 0,this.pf.rf=void 0)},isDeleted:function(){return!this.pf.rf},deleteLater:function(){this.pf.rf||Sa(this);if(this.pf.bg&&!this.pf.dg)throw new L("Object already scheduled for deletion");Wa.push(this);this.pf.bg=!0;return this}});
const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(nb.prototype,{fh(a){this.Lg&&(a=this.Lg(a));return a},Dg(a){this.If?.(a)},Ef:Ma,uf:function(a){function b(){return this.kg?mb(this.sf.Of,{vf:this.qh,rf:c,Cf:this,zf:a}):mb(this.sf.Of,{vf:this,rf:a})}var c=this.fh(a);if(!c)return this.Dg(a),null;var d=lb(this.sf,c);if(void 0!==d){if(0===d.pf.count.value)return d.pf.rf=c,d.pf.zf=a,d.clone();d=d.clone();this.Dg(a);return d}d=this.sf.eh(c);d=Za[d];if(!d)return b.call(this);d=this.jg?d.Wg:d.pointerType;var e=jb(c,this.sf,d.sf);return null===
e?b.call(this):this.kg?mb(d.sf.Of,{vf:d,rf:e,Cf:this,zf:a}):mb(d.sf.Of,{vf:d,rf:e})}});var Pc=()=>V.ph();"undefined"!=typeof MainLoop&&MainLoop.Jh.push(Pc);for(let a=0;32>a;++a)hc.push(Array(a));for(var Qc=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=Qc.subarray(0,Y);var Rc=new Int32Array(288);for(Y=0;288>=Y;++Y)Fc[Y]=Rc.subarray(0,Y);f.noExitRuntime&&(Ea=f.noExitRuntime);f.print&&(ia=f.print);f.printErr&&(g=f.printErr);f.wasmBinary&&(ja=f.wasmBinary);f.thisProgram&&(ca=f.thisProgram);
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();f.ccall=Oc;f.cwrap=(a,b,c,d)=>{var e=!c||c.every(h=>"number"===h||"boolean"===h);return"string"!==b&&e&&!d?f["_"+a]:(...h)=>Oc(a,b,c,h,d)};
f.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":n[a>>>0]=b;break;case "i8":n[a>>>0]=b;break;case "i16":t[a>>>1>>>0]=b;break;case "i32":w[a>>>2>>>0]=b;break;case "i64":pa[a>>>3>>>0]=BigInt(b);break;case "float":y[a>>>2>>>0]=b;break;case "double":oa[a>>>3>>>0]=b;break;case "*":x[a>>>2>>>0]=b;break;default:ua(`invalid type for setValue: ${c}`)}};
f.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return n[a>>>0];case "i8":return n[a>>>0];case "i16":return t[a>>>1>>>0];case "i32":return w[a>>>2>>>0];case "i64":return pa[a>>>3>>>0];case "float":return y[a>>>2>>>0];case "double":return oa[a>>>3>>>0];case "*":return x[a>>>2>>>0];default:ua(`invalid type for getValue: ${b}`)}};f.GL=V;
var tb,vc,O,Sc,Nc,Lc,Mc,ta,pb,Tc={k:function(a,b,c){a>>>=0;var d=new Fa(a);x[d.rf+16>>>2>>>0]=0;x[d.rf+4>>>2>>>0]=b>>>0;x[d.rf+8>>>2>>>0]=c>>>0;Ga=a;Ha++;throw Ga;},p:function(){return 0},Ua:function(){},Xa:function(){return 0},Ya:function(){},$a:()=>ua(""),bf:function(a){a>>>=0;var b=Ka[a];delete Ka[a];var c=b.xg,d=b.If,e=b.Eg,h=e.map(k=>k.lh).concat(e.map(k=>k.vh));I([a],h,k=>{var l={};e.forEach((m,q)=>{var p=k[q],v=m.jh,z=m.kh,C=k[q+e.length],D=m.uh,E=m.wh;l[m.bh]={read:K=>p.uf(v(z,K)),write:(K,
P)=>{var F=[];D(E,K,C.wf(F,P));La(F)},optional:k[q].optional}});return[{name:b.name,uf:m=>{var q={},p;for(p in l)q[p]=l[p].read(m);d(m);return q},wf:(m,q)=>{for(var p in l)if(!(p in q||l[p].optional))throw new TypeError(`Missing field: "${p}"`);var v=c();for(p in l)l[p].write(v,q[p]);null!==m&&m.push(d,v);return v},Ef:Ma,Bf:d}]})},u:function(a,b,c,d,e){a>>>=0;c>>>=0;b=J(b>>>0);d=0n===d;let h=k=>k;if(d){const k=8*c;h=l=>BigInt.asUintN(k,l);e=h(e)}H(a,{name:b,uf:h,wf:(k,l)=>{"number"==typeof l&&(l=
BigInt(l));return l},Ef:Ra(b,c,!d),Bf:null})},Re:function(a,b,c,d){b=J(b>>>0);H(a>>>0,{name:b,uf:function(e){return!!e},wf:function(e,h){return h?c:d},Ef:function(e){return this.uf(r[e>>>0])},Bf:null})},j:function(a,b,c,d,e,h,k,l,m,q,p,v,z){a>>>=0;b>>>=0;c>>>=0;d>>>=0;h>>>=0;k>>>=0;l>>>=0;m>>>=0;q>>>=0;p>>>=0;v>>>=0;z>>>=0;p=J(p);h=N(e>>>0,h);l&&=N(k,l);q&&=N(m,q);z=N(v,z);var C=bb(p);ab(C,function(){vb(`Cannot construct ${p} due to unbound types`,[d])});I([a,b,c],d?[d]:[],D=>{D=D[0];if(d){var E=
D.sf;var K=E.Of}else K=Xa.prototype;D=Ya(p,function(...cb){if(Object.getPrototypeOf(this)!==P)throw new L(`Use 'new' to construct ${p}`);if(void 0===F.Sf)throw new L(`${p} has no accessible constructor`);var Zb=F.Sf[cb.length];if(void 0===Zb)throw new L(`Tried to invoke ctor of ${p} with invalid number of parameters (${cb.length}) - expected (${Object.keys(F.Sf).toString()}) parameters instead!`);return Zb.apply(this,cb)});var P=Object.create(K,{constructor:{value:D}});D.prototype=P;var F=new db(p,
D,P,z,E,h,l,q);if(F.Af){var U;(U=F.Af).Ag??(U.Ag=[]);F.Af.Ag.push(F)}E=new nb(p,F,!0,!1,!1);U=new nb(p+"*",F,!1,!1,!1);K=new nb(p+" const*",F,!1,!0,!1);Za[a]={pointerType:U,Wg:K};ob(C,D);return[E,U,K]})},i:function(a,b,c,d,e,h){a>>>=0;d>>>=0;e>>>=0;h>>>=0;var k=wb(b,c>>>0);e=N(d,e);I([],[a],l=>{l=l[0];var m=`constructor ${l.name}`;void 0===l.sf.Sf&&(l.sf.Sf=[]);if(void 0!==l.sf.Sf[b-1])throw new L(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${l.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
l.sf.Sf[b-1]=()=>{vb(`Cannot construct ${l.name} due to unbound types`,k)};I([],k,q=>{q.splice(1,0,null);l.sf.Sf[b-1]=yb(m,q,null,e,h);return[]});return[]})},e:function(a,b,c,d,e,h,k,l,m){a>>>=0;b>>>=0;e>>>=0;h>>>=0;k>>>=0;var q=wb(c,d>>>0);b=J(b);b=zb(b);h=N(e,h);I([],[a],p=>{function v(){vb(`Cannot call ${z} due to unbound types`,q)}p=p[0];var z=`${p.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&p.sf.rh.push(b);var C=p.sf.Of,D=C[b];void 0===D||void 0===D.Mf&&D.className!==p.name&&
D.Zf===c-2?(v.Zf=c-2,v.className=p.name,C[b]=v):($a(C,b,z),C[b].Mf[c-2]=v);I([],q,E=>{E=yb(z,E,p,h,k,m);void 0===C[b].Mf?(E.Zf=c-2,C[b]=E):C[b].Mf[c-2]=E;return[]});return[]})},b:function(a,b,c,d,e,h,k,l,m,q){a>>>=0;b>>>=0;c>>>=0;e>>>=0;h>>>=0;k>>>=0;l>>>=0;m>>>=0;q>>>=0;b=J(b);e=N(d>>>0,e);I([],[a],p=>{p=p[0];var v=`${p.name}.${b}`,z={get(){vb(`Cannot access ${v} due to unbound types`,[c,k])},enumerable:!0,configurable:!0};z.set=m?()=>vb(`Cannot access ${v} due to unbound types`,[c,k]):()=>{throw new L(v+
" is a read-only property");};Object.defineProperty(p.sf.Of,b,z);I([],m?[c,k]:[c],C=>{var D=C[0],E={get(){var P=Ab(this,p,v+" getter");return D.uf(e(h,P))},enumerable:!0};if(m){m=N(l,m);var K=C[1];E.set=function(P){var F=Ab(this,p,v+" setter"),U=[];m(q,F,K.wf(U,P));La(U)}}Object.defineProperty(p.sf.Of,b,E);return[]});return[]})},s:function(a,b,c){a>>>=0;a=J(a);I([],[b>>>0],d=>{d=d[0];f[a]=d.uf(c);return[]})},le:function(a){return H(a>>>0,Db)},d:function(a,b,c,d){function e(){}b=J(b>>>0);e.values=
{};H(a>>>0,{name:b,constructor:e,uf:function(h){return this.constructor.values[h]},wf:(h,k)=>k.value,Ef:Eb(b,c>>>0,d),Bf:null});ab(b,e)},a:function(a,b,c){b>>>=0;var d=Fb(a>>>0,"enum");b=J(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ya(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},t:function(a,b,c){b=J(b>>>0);H(a>>>0,{name:b,uf:d=>d,wf:(d,e)=>e,Ef:Gb(b,c>>>0),Bf:null})},f:function(a,b,c,d,e){a>>>=0;c>>>=0;b=J(b>>>0);let h=l=>l;if(0===d){var k=
32-8*c;h=l=>l<<k>>>k;e=h(e)}H(a,{name:b,uf:h,wf:(l,m)=>m,Ef:Ra(b,c,0!==d),Bf:null})},c:function(a,b,c){function d(h){return new e(n.buffer,x[h+4>>>2>>>0],x[h>>>2>>>0])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=J(c>>>0);H(a>>>0,{name:c,uf:d,Ef:d},{mh:!0})},Ge:function(a,b){b=J(b>>>0);H(a>>>0,{name:b,uf(c){var d=A(c+4,x[c>>>2>>>0],!0);O(c);return d},wf(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e=
"string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new L("Cannot pass non-string to std::string");var h=e?Hb(d):d.length;var k=vc(4+h+1),l=k+4;x[k>>>2>>>0]=h;e?S(d,l,h+1):r.set(d,l>>>0);null!==c&&c.push(O,k);return k},Ef:Ma,Bf(c){O(c)}})},n:function(a,b,c){b>>>=0;c>>>=0;c=J(c);if(2===b){var d=Jb;var e=Kb;var h=Lb}else d=Mb,e=Nb,h=Ob;H(a>>>0,{name:c,uf:k=>{var l=d(k+4,x[k>>>2>>>0]*b,!0);O(k);return l},wf:(k,l)=>{if("string"!=typeof l)throw new L(`Cannot pass non-string to C++ string type ${c}`);
var m=h(l),q=vc(4+m+b);x[q>>>2>>>0]=m/b;e(l,q+4,m+b);null!==k&&k.push(O,q);return q},Ef:Ma,Bf(k){O(k)}})},ed:function(a,b,c,d,e,h){e>>>=0;h>>>=0;Ka[a>>>0]={name:J(b>>>0),xg:N(c>>>0,d>>>0),If:N(e,h),Eg:[]}},m:function(a,b,c,d,e,h,k,l,m,q){h>>>=0;k>>>=0;l>>>=0;m>>>=0;q>>>=0;Ka[a>>>0].Eg.push({bh:J(b>>>0),lh:c>>>0,jh:N(d>>>0,e>>>0),kh:h,vh:k,uh:N(l,m),wh:q})},af:function(a,b){b=J(b>>>0);H(a>>>0,{Fg:!0,name:b,uf:()=>{},wf:()=>{}})},Ma:()=>{Ea=!1;Pb=0},h:function(a,b,c){var [d,...e]=Sb(a,b>>>0);b=d.wf.bind(d);
var h=e.map(m=>m.Ef.bind(m));a--;var k={toValue:R};a=h.map((m,q)=>{var p=`argFromPtr${q}`;k[p]=m;return`${p}(args${q?"+"+8*q:""})`});switch(c){case 0:var l="toValue(handle)";break;case 2:l="new (toValue(handle))";break;case 3:l="";break;case 1:k.getStringOrSymbol=Vb,l="toValue(handle)[getStringOrSymbol(methodName)]"}l+=`(${a})`;d.Fg||(k.toReturnWire=b,k.emval_returnValue=Tb,l=`return emval_returnValue(toReturnWire, destructorsRef, ${l})`);l=`return function (handle, methodName, destructorsRef, args) {\n  ${l}\n  }`;
c=(new Function(Object.keys(k),l))(...Object.values(k));l=`methodCaller<(${e.map(m=>m.name)}) => ${d.name}>`;return Rb(Ya(l,c))},ta:Cb,hc:function(a){a=Vb(a>>>0);return M(f[a])},r:function(a,b){b>>>=0;a=R(a>>>0);b=R(b);return M(a[b])},Q:function(a){a>>>=0;9<a&&(Q[a+1]+=1)},g:function(a,b,c,d,e){return Qb[a>>>0](b>>>0,c>>>0,d>>>0,e>>>0)},Yb:function(a){return M(Vb(a>>>0))},Db:function(){return M({})},F:function(a){a>>>=0;var b=R(a);La(b);Cb(a)},q:function(a,b,c){b>>>=0;c>>>=0;a=R(a>>>0);b=R(b);c=R(c);
a[b]=c},Na:(a,b)=>{Wb[a]&&(clearTimeout(Wb[a].id),delete Wb[a]);if(!b)return 0;var c=setTimeout(()=>{delete Wb[a];$b(()=>Sc(a,performance.now()))},b);Wb[a]={id:c,Mh:b};return 0},Oa:function(a,b,c,d){c>>>=0;d>>>=0;var e=(new Date).getFullYear(),h=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();x[a>>>0>>>2>>>0]=60*Math.max(h,e);w[b>>>0>>>2>>>0]=Number(h!=e);b=k=>{var l=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,
"0")}`};a=b(h);b=b(e);e<h?(S(a,c,17),S(b,d,17)):(S(a,d,17),S(b,c,17))},Za:()=>Date.now(),sa:a=>T.activeTexture(a),ra:(a,b)=>{T.attachShader(V.tf[a],V.yf[b])},Sc:(a,b)=>{T.beginQuery(a,V.xf[b])},Ja:(a,b)=>{T.Df.beginQueryEXT(a,V.xf[b])},vc:a=>T.beginTransformFeedback(a),qa:function(a,b,c){T.bindAttribLocation(V.tf[a],b,A(c>>>0))},pa:(a,b)=>{if(b&&!V.Gf[b]){var c=T.createBuffer();c.name=b;V.Gf[b]=c}34962==a?T.$f=b:34963==a&&(T.ag=b);35051==a?T.sg=b:35052==a&&(T.Hf=b);T.bindBuffer(a,V.Gf[b])},sc:(a,
b,c)=>{T.bindBufferBase(a,b,V.Gf[c])},tc:function(a,b,c,d,e){T.bindBufferRange(a,b,V.Gf[c],d>>>0,e>>>0)},oa:(a,b)=>{T.bindFramebuffer(a,V.cg[b])},na:(a,b)=>{T.bindRenderbuffer(a,V.Wf[b])},xb:(a,b)=>{T.bindSampler(a,V.Ff[b])},ma:(a,b)=>{T.bindTexture(a,V.Tf[b])},pb:(a,b)=>{T.bindTransformFeedback(a,V.fg[b])},Ac:ec,Ba:ec,la:(a,b,c,d)=>T.blendColor(a,b,c,d),ka:a=>T.blendEquation(a),ja:(a,b)=>T.blendEquationSeparate(a,b),ia:(a,b)=>T.blendFunc(a,b),ha:(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),Fc:(a,b,c,
d,e,h,k,l,m,q)=>T.blitFramebuffer(a,b,c,d,e,h,k,l,m,q),ga:function(a,b,c,d){b>>>=0;c>>>=0;T.bufferData(a,c?r.subarray(c>>>0,c+b>>>0):b,d)},fa:function(a,b,c,d){d>>>=0;T.bufferSubData(a,b>>>0,r.subarray(d>>>0,d+(c>>>0)>>>0))},ea:a=>T.checkFramebufferStatus(a),da:a=>T.clear(a),Vb:(a,b,c,d)=>T.clearBufferfi(a,b,c,d),Wb:function(a,b,c){T.clearBufferfv(a,b,y,c>>>0>>>2)},Zb:function(a,b,c){T.clearBufferiv(a,b,w,c>>>0>>>2)},Xb:function(a,b,c){T.clearBufferuiv(a,b,x,c>>>0>>>2)},ca:(a,b,c,d)=>T.clearColor(a,
b,c,d),ba:a=>T.clearDepth(a),aa:a=>T.clearStencil(a),Hb:function(a,b,c){c=Number(c);return T.clientWaitSync(V.Qf[a>>>0],b,c)},ld:(a,b)=>{T.$g.clipControlEXT(a,b)},$:(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},_:a=>{T.compileShader(V.yf[a])},Z:function(a,b,c,d,e,h,k,l){l>>>=0;2<=V.qf.version&&(T.Hf||!k)?T.compressedTexImage2D(a,b,c,d,e,h,k,l):T.compressedTexImage2D(a,b,c,d,e,h,r.subarray(l>>>0,l+k>>>0))},Xc:function(a,b,c,d,e,h,k,l,m){m>>>=0;T.Hf?T.compressedTexImage3D(a,b,c,d,e,h,k,l,m):T.compressedTexImage3D(a,
b,c,d,e,h,k,r,m,l)},Y:function(a,b,c,d,e,h,k,l,m){m>>>=0;2<=V.qf.version&&(T.Hf||!l)?T.compressedTexSubImage2D(a,b,c,d,e,h,k,l,m):T.compressedTexSubImage2D(a,b,c,d,e,h,k,r.subarray(m>>>0,m+l>>>0))},Wc:function(a,b,c,d,e,h,k,l,m,q,p){p>>>=0;T.Hf?T.compressedTexSubImage3D(a,b,c,d,e,h,k,l,m,q,p):T.compressedTexSubImage3D(a,b,c,d,e,h,k,l,m,r,p,q)},Tb:function(a,b,c,d,e){return T.copyBufferSubData(a,b,c>>>0,d>>>0,e>>>0)},X:(a,b,c,d,e,h,k,l)=>T.copyTexImage2D(a,b,c,d,e,h,k,l),W:(a,b,c,d,e,h,k,l)=>T.copyTexSubImage2D(a,
b,c,d,e,h,k,l),Yc:(a,b,c,d,e,h,k,l,m)=>T.copyTexSubImage3D(a,b,c,d,e,h,k,l,m),V:()=>{var a=V.Vf(V.tf),b=T.createProgram();b.name=a;b.pg=b.ng=b.og=0;b.yg=1;V.tf[a]=b;return a},U:a=>{var b=V.Vf(V.yf);V.yf[b]=T.createShader(a);return b},T:a=>T.cullFace(a),S:function(a,b){b>>>=0;for(var c=0;c<a;c++){var d=w[b+4*c>>>2>>>0],e=V.Gf[d];e&&(T.deleteBuffer(e),e.name=0,V.Gf[d]=null,d==T.$f&&(T.$f=0),d==T.ag&&(T.ag=0),d==T.sg&&(T.sg=0),d==T.Hf&&(T.Hf=0))}},R:function(a,b){b>>>=0;for(var c=0;c<a;++c){var d=w[b+
4*c>>>2>>>0],e=V.cg[d];e&&(T.deleteFramebuffer(e),e.name=0,V.cg[d]=null)}},P:a=>{if(a){var b=V.tf[a];b?(T.deleteProgram(b),b.name=0,V.tf[a]=null):V.nf(1281)}},Uc:function(a,b){b>>>=0;for(var c=0;c<a;c++){var d=w[b+4*c>>>2>>>0],e=V.xf[d];e&&(T.deleteQuery(e),V.xf[d]=null)}},Ra:function(a,b){b>>>=0;for(var c=0;c<a;c++){var d=w[b+4*c>>>2>>>0],e=V.xf[d];e&&(T.Df.deleteQueryEXT(e),V.xf[d]=null)}},O:function(a,b){b>>>=0;for(var c=0;c<a;c++){var d=w[b+4*c>>>2>>>0],e=V.Wf[d];e&&(T.deleteRenderbuffer(e),e.name=
0,V.Wf[d]=null)}},zb:function(a,b){b>>>=0;for(var c=0;c<a;c++){var d=w[b+4*c>>>2>>>0],e=V.Ff[d];e&&(T.deleteSampler(e),e.name=0,V.Ff[d]=null)}},N:a=>{if(a){var b=V.yf[a];b?(T.deleteShader(b),V.yf[a]=null):V.nf(1281)}},Ib:function(a){if(a>>>=0){var b=V.Qf[a];b?(T.deleteSync(b),b.name=0,V.Qf[a]=null):V.nf(1281)}},M:function(a,b){b>>>=0;for(var c=0;c<a;c++){var d=w[b+4*c>>>2>>>0],e=V.Tf[d];e&&(T.deleteTexture(e),e.name=0,V.Tf[d]=null)}},ob:function(a,b){b>>>=0;for(var c=0;c<a;c++){var d=w[b+4*c>>>2>>>
0],e=V.fg[d];e&&(T.deleteTransformFeedback(e),e.name=0,V.fg[d]=null)}},zc:fc,Aa:fc,L:a=>T.depthFunc(a),K:a=>{T.depthMask(!!a)},J:(a,b)=>T.depthRange(a,b),I:(a,b)=>{T.detachShader(V.tf[a],V.yf[b])},H:a=>T.disable(a),G:a=>{V.qf.Kf[a].enabled=!1;T.disableVertexAttribArray(a)},E:(a,b,c)=>{V.Kg(b+c);T.drawArrays(a,b,c);V.Jg()},Mb:gc,wa:gc,gd:gc,hd:gc,ab:gc,Mc:ic,bd:ic,xa:ic,D:jc,Lb:kc,va:kc,cd:kc,dd:kc,fd:kc,$c:function(a,b,c,d,e,h){jc(a,d,e,h>>>0)},C:a=>T.enable(a),B:a=>{V.qf.Kf[a].enabled=!0;T.enableVertexAttribArray(a)},
Rc:a=>T.endQuery(a),Ia:a=>{T.Df.endQueryEXT(a)},uc:()=>T.endTransformFeedback(),Kb:function(a,b){return(a=T.fenceSync(a,b))?(b=V.Vf(V.Qf),a.name=b,V.Qf[b]=a,b):0},A:()=>T.finish(),z:()=>T.flush(),Bc:function(a,b,c){b>>>=0;c>>>=0;if(mc(a)){var d=V.mg[lc(a)];d?d.Bg&16?0>b||0>c||b+c>d.length?(V.nf(1281),g("invalid range in glFlushMappedBufferRange")):T.bufferSubData(a,d.offset,r.subarray(d.Pf+b>>>0,d.Pf+b+c>>>0)):(V.nf(1282),g("buffer was not mapped with GL_MAP_FLUSH_EXPLICIT_BIT in glFlushMappedBufferRange")):
(V.nf(1282),g("buffer was never mapped in glFlushMappedBufferRange"))}else V.nf(1280),g("GL_INVALID_ENUM in glFlushMappedBufferRange")},y:(a,b,c,d)=>{T.framebufferRenderbuffer(a,b,c,V.Wf[d])},x:(a,b,c,d,e)=>{T.framebufferTexture2D(a,b,c,V.Tf[d],e)},Dc:(a,b,c,d,e)=>{T.framebufferTextureLayer(a,b,V.Tf[c],d,e)},w:a=>T.frontFace(a),v:function(a,b){V.Nf(a,b>>>0,"createBuffer",V.Gf)},_e:function(a,b){V.Nf(a,b>>>0,"createFramebuffer",V.cg)},Vc:function(a,b){V.Nf(a,b>>>0,"createQuery",V.xf)},_a:function(a,
b){b>>>=0;for(var c=0;c<a;c++){var d=T.Df.createQueryEXT();if(!d){for(V.nf(1282);c<a;)w[b+4*c++>>>2>>>0]=0;break}var e=V.Vf(V.xf);d.name=e;V.xf[e]=d;w[b+4*c>>>2>>>0]=e}},Ze:function(a,b){V.Nf(a,b>>>0,"createRenderbuffer",V.Wf)},Ab:function(a,b){V.Nf(a,b>>>0,"createSampler",V.Ff)},Ye:function(a,b){V.Nf(a,b>>>0,"createTexture",V.Tf)},nb:function(a,b){V.Nf(a,b>>>0,"createTransformFeedback",V.fg)},yc:nc,za:nc,$e:a=>T.generateMipmap(a),Xe:function(a,b,c,d,e,h,k){return oc("getActiveAttrib",a,b,c,d>>>0,
e>>>0,h>>>0,k>>>0)},We:function(a,b,c,d,e,h,k){return oc("getActiveUniform",a,b,c,d>>>0,e>>>0,h>>>0,k>>>0)},Ob:function(a,b,c,d,e){d>>>=0;e>>>=0;a=V.tf[a];if(a=T.getActiveUniformBlockName(a,b))e&&0<c?(c=S(a,e,c),d&&(w[d>>>2>>>0]=c)):d&&(w[d>>>2>>>0]=0)},Pb:function(a,b,c,d){if(d>>>=0)if(a=V.tf[a],35393==c)w[d>>>2>>>0]=T.getActiveUniformBlockName(a,b).length+1;else{if(a=T.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)w[d+4*c>>>2>>>0]=a[c];else w[d>>>2>>>0]=a}else V.nf(1281)},
Rb:function(a,b,c,d,e){c>>>=0;if(e>>>=0)if(0<b&&0==c)V.nf(1281);else{a=V.tf[a];for(var h=[],k=0;k<b;k++)h.push(w[c+4*k>>>2>>>0]);if(a=T.getActiveUniforms(a,h,d))for(b=a.length,k=0;k<b;k++)w[e+4*k>>>2>>>0]=a[k]}else V.nf(1281)},Ve:function(a,b,c,d){d>>>=0;a=T.getAttachedShaders(V.tf[a]);var e=a.length;e>b&&(e=b);w[c>>>0>>>2>>>0]=e;for(b=0;b<e;++b)w[d+4*b>>>2>>>0]=V.yf.indexOf(a[b])},Ue:function(a,b){return T.getAttribLocation(V.tf[a],A(b>>>0))},Te:function(a,b){return rc(a,b>>>0,4)},Bb:function(a,
b,c){(c>>>=0)?pc(c,T.getBufferParameter(a,b)):V.nf(1281)},Se:function(a,b,c){(c>>>=0)?w[c>>>2>>>0]=T.getBufferParameter(a,b):V.nf(1281)},Nc:function(a,b,c){c>>>=0;if(35005==b){b=0;if(a=V.mg[lc(a)])b=a.Pf;w[c>>>2>>>0]=b}else V.nf(1280),g("GL_INVALID_ENUM in glGetBufferPointerv")},Qe:()=>{var a=T.getError()||V.ug;V.ug=0;return a},Pe:function(a,b){return rc(a,b>>>0,2)},gc:function(a,b){return T.getFragDataLocation(V.tf[a],A(b>>>0))},Oe:function(a,b,c,d){a=T.getFramebufferAttachmentParameter(a,b,c);if(a instanceof
WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;w[d>>>0>>>2>>>0]=a},Cb:function(a,b,c){return sc(a,b,c>>>0,1)},Fb:function(a,b){rc(a,b>>>0,1)},wc:function(a,b,c){return sc(a,b,c>>>0,0)},Ne:function(a,b){return rc(a,b>>>0,0)},cb:function(a,b,c,d,e){e>>>=0;if(0>d)V.nf(1281);else if(e){if(a=T.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)w[e+4*b>>>2>>>0]=a[b]}else V.nf(1281)},jb:function(){V.nf(1282)},Le:function(a,b,c,d){c>>>=0;d>>>=0;a=T.getProgramInfoLog(V.tf[a]);
null===a&&(a="(unknown error)");b=0<b&&d?S(a,d,b):0;c&&(w[c>>>2>>>0]=b)},Me:function(a,b,c){if(c>>>=0)if(a>=V.counter)V.nf(1281);else if(a=V.tf[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>>2>>>0]=a.length+1;else if(35719==b){if(!a.pg){var d=T.getProgramParameter(a,35718);for(b=0;b<d;++b)a.pg=Math.max(a.pg,T.getActiveUniform(a,b).name.length+1)}w[c>>>2>>>0]=a.pg}else if(35722==b){if(!a.ng)for(d=T.getProgramParameter(a,35721),b=0;b<d;++b)a.ng=Math.max(a.ng,T.getActiveAttrib(a,
b).name.length+1);w[c>>>2>>>0]=a.ng}else if(35381==b){if(!a.og)for(d=T.getProgramParameter(a,35382),b=0;b<d;++b)a.og=Math.max(a.og,T.getActiveUniformBlockName(a,b).length+1);w[c>>>2>>>0]=a.og}else w[c>>>2>>>0]=T.getProgramParameter(a,b);else V.nf(1281)},Da:tc,Fa:uc,Ca:tc,Pc:function(a,b,c){if(c>>>=0){a=T.getQueryParameter(V.xf[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>>2>>>0]=d}else V.nf(1281)},Ea:uc,Qc:function(a,b,c){(c>>>=0)?w[c>>>2>>>0]=T.getQuery(a,b):V.nf(1281)},Ga:function(a,b,c){(c>>>=
0)?w[c>>>2>>>0]=T.Df.getQueryEXT(a,b):V.nf(1281)},Ke:function(a,b,c){(c>>>=0)?w[c>>>2>>>0]=T.getRenderbufferParameter(a,b):V.nf(1281)},rb:function(a,b,c){(c>>>=0)?y[c>>>2>>>0]=T.getSamplerParameter(V.Ff[a],b):V.nf(1281)},sb:function(a,b,c){(c>>>=0)?w[c>>>2>>>0]=T.getSamplerParameter(V.Ff[a],b):V.nf(1281)},Ie:function(a,b,c,d){c>>>=0;d>>>=0;a=T.getShaderInfoLog(V.yf[a]);null===a&&(a="(unknown error)");b=0<b&&d?S(a,d,b):0;c&&(w[c>>>2>>>0]=b)},He:function(a,b,c,d){c>>>=0;a=T.getShaderPrecisionFormat(a,
b);w[c>>>2>>>0]=a.rangeMin;w[c+4>>>2>>>0]=a.rangeMax;w[d>>>0>>>2>>>0]=a.precision},Fe:function(a,b,c,d){c>>>=0;d>>>=0;if(a=T.getShaderSource(V.yf[a]))b=0<b&&d?S(a,d,b):0,c&&(w[c>>>2>>>0]=b)},Je:function(a,b,c){(c>>>=0)?35716==b?(a=T.getShaderInfoLog(V.yf[a]),null===a&&(a="(unknown error)"),w[c>>>2>>>0]=a?a.length+1:0):35720==b?(a=T.getShaderSource(V.yf[a]),w[c>>>2>>>0]=a?a.length+1:0):w[c>>>2>>>0]=T.getShaderParameter(V.yf[a],b):V.nf(1281)},Ee:function(a){var b=V.Ng[a];if(!b){switch(a){case 7939:b=
wc(qc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=T.getParameter(a))||V.nf(1280);b=b?wc(b):0;break;case 7938:b=T.getParameter(7938);var c=`OpenGL ES 2.0 (${b})`;2<=V.qf.version&&(c=`OpenGL ES 3.0 (${b})`);b=wc(c);break;case 35724:b=T.getParameter(35724);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=wc(b);break;default:V.nf(1280)}V.Ng[a]=b}return b},Ub:function(a,b){if(2>V.qf.version)return V.nf(1282),
0;var c=V.Og[a];if(c)return 0>b||b>=c.length?(V.nf(1281),0):c[b];switch(a){case 7939:return c=qc().map(wc),c=V.Og[a]=c,0>b||b>=c.length?(V.nf(1281),0):c[b];default:return V.nf(1280),0}},Eb:function(a,b,c,d,e){a>>>=0;d>>>=0;e>>>=0;0>c?V.nf(1281):e?(a=T.getSyncParameter(V.Qf[a],b),null!==a&&(w[e>>>2>>>0]=a,d&&(w[d>>>2>>>0]=1))):V.nf(1281)},De:function(a,b,c){(c>>>=0)?y[c>>>2>>>0]=T.getTexParameter(a,b):V.nf(1281)},Ce:function(a,b,c){(c>>>=0)?w[c>>>2>>>0]=T.getTexParameter(a,b):V.nf(1281)},qc:function(a,
b,c,d,e,h,k){d>>>=0;e>>>=0;h>>>=0;k>>>=0;a=V.tf[a];if(a=T.getTransformFeedbackVarying(a,b))k&&0<c?(c=S(a.name,k,c),d&&(w[d>>>2>>>0]=c)):d&&(w[d>>>2>>>0]=0),e&&(w[e>>>2>>>0]=a.size),h&&(w[h>>>2>>>0]=a.type)},Qb:function(a,b){return T.getUniformBlockIndex(V.tf[a],A(b>>>0))},Sb:function(a,b,c,d){c>>>=0;if(d>>>=0)if(0<b&&(0==c||0==d))V.nf(1281);else{a=V.tf[a];for(var e=[],h=0;h<b;h++)e.push(A(w[c+4*h>>>2>>>0]));if(a=T.getUniformIndices(a,e))for(b=a.length,h=0;h<b;h++)w[d+4*h>>>2>>>0]=a[h]}else V.nf(1281)},
ze:function(a,b){b=A(b>>>0);if(a=V.tf[a]){yc(a);var c=a.gg,d=0,e=b,h=xc(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Qg[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else V.nf(1281);return-1},Be:function(a,b,c){zc(a,b,c>>>0,2)},Ae:function(a,b,c){zc(a,b,c>>>0,0)},ic:function(a,b,c){return zc(a,b,c>>>0,0)},oc:Bc,nc:Bc,we:function(a,b,c){(c>>>=0)?(V.qf.Kf[a].enabled&&g("glGetVertexAttribPointer on client-side array: not supported, bad data returned"),w[c>>>2>>>
0]=T.getVertexAttribOffset(a,b)):V.nf(1281)},ye:function(a,b,c){Ac(a,b,c>>>0,2)},xe:function(a,b,c){Ac(a,b,c>>>0,5)},ve:(a,b)=>T.hint(a,b),gb:function(a,b,c){c>>>=0;for(var d=hc[b],e=0;e<b;e++)d[e]=w[c+4*e>>>2>>>0];T.invalidateFramebuffer(a,d)},fb:function(a,b,c,d,e,h,k){c>>>=0;for(var l=hc[b],m=0;m<b;m++)l[m]=w[c+4*m>>>2>>>0];T.invalidateSubFramebuffer(a,l,d,e,h,k)},ue:a=>(a=V.Gf[a])?T.isBuffer(a):0,te:a=>T.isEnabled(a),se:a=>(a=V.cg[a])?T.isFramebuffer(a):0,re:a=>(a=V.tf[a])?T.isProgram(a):0,Tc:a=>
(a=V.xf[a])?T.isQuery(a):0,Ka:a=>(a=V.xf[a])?T.Df.isQueryEXT(a):0,qe:a=>(a=V.Wf[a])?T.isRenderbuffer(a):0,yb:a=>(a=V.Ff[a])?T.isSampler(a):0,pe:a=>(a=V.yf[a])?T.isShader(a):0,Jb:function(a){return T.isSync(V.Qf[a>>>0])},oe:a=>(a=V.Tf[a])?T.isTexture(a):0,mb:a=>T.isTransformFeedback(V.fg[a]),xc:Cc,ya:Cc,ne:a=>T.lineWidth(a),me:a=>{a=V.tf[a];T.linkProgram(a);a.gg=0;a.Qg={}},Cc:function(a,b,c,d){b>>>=0;c>>>=0;if(0!=(d&33))return g("glMapBufferRange access does not support MAP_READ or MAP_UNSYNCHRONIZED"),
0;if(0==(d&2))return g("glMapBufferRange access must include MAP_WRITE"),0;if(0==(d&12))return g("glMapBufferRange access must include INVALIDATE_BUFFER or INVALIDATE_RANGE"),0;if(!mc(a))return V.nf(1280),g("GL_INVALID_ENUM in glMapBufferRange"),0;var e=vc(c);a=lc(a);if(!e)return 0;let h,k;a=(h=V.mg)[k=a]??(h[k]={});a.offset=b;a.length=c;a.Pf=e;a.Bg=d;return e},lb:()=>T.pauseTransformFeedback(),ke:(a,b)=>{3317==a?V.Rg=b:3314==a&&(V.Sg=b);T.pixelStorei(a,b)},kd:(a,b)=>{T.zh.polygonModeWEBGL(a,b)},
je:(a,b)=>T.polygonOffset(a,b),md:(a,b,c)=>{T.ah.polygonOffsetClampEXT(a,b,c)},ib:function(){V.nf(1280)},hb:()=>{V.nf(1280)},Ha:(a,b)=>{T.Df.queryCounterEXT(V.xf[a],b)},ad:a=>T.readBuffer(a),ie:function(a,b,c,d,e,h,k){k>>>=0;2<=V.qf.version&&T.sg?T.readPixels(a,b,c,d,e,h,k):(k=Ec(h,e,c,d,k))?T.readPixels(a,b,c,d,e,h,k):V.nf(1280)},he:()=>{},ge:(a,b,c,d)=>T.renderbufferStorage(a,b,c,d),Ec:(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,b,c,d,e),kb:()=>T.resumeTransformFeedback(),fe:(a,b)=>{T.sampleCoverage(a,
!!b)},ub:(a,b,c)=>{T.samplerParameterf(V.Ff[a],b,c)},tb:function(a,b,c){T.samplerParameterf(V.Ff[a],b,y[c>>>0>>>2>>>0])},wb:(a,b,c)=>{T.samplerParameteri(V.Ff[a],b,c)},vb:function(a,b,c){T.samplerParameteri(V.Ff[a],b,w[c>>>0>>>2>>>0])},ee:(a,b,c,d)=>T.scissor(a,b,c,d),de:function(){V.nf(1280)},ce:function(a,b,c,d){b=V.gh(a,b,c>>>0,d>>>0);T.shaderSource(V.yf[a],b)},be:(a,b,c)=>T.stencilFunc(a,b,c),ae:(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,d),$d:a=>T.stencilMask(a),_d:(a,b)=>T.stencilMaskSeparate(a,
b),Zd:(a,b,c)=>T.stencilOp(a,b,c),Yd:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),Xd:function(a,b,c,d,e,h,k,l,m){m>>>=0;2<=V.qf.version&&T.Hf?T.texImage2D(a,b,c,d,e,h,k,l,m):(m=m?Ec(l,k,d,e,m):null,T.texImage2D(a,b,c,d,e,h,k,l,m))},_c:function(a,b,c,d,e,h,k,l,m,q){q>>>=0;T.Hf?T.texImage3D(a,b,c,d,e,h,k,l,m,q):q?(q=Ec(m,l,d,e*h,q),T.texImage3D(a,b,c,d,e,h,k,l,m,q)):T.texImage3D(a,b,c,d,e,h,k,l,m,null)},Wd:(a,b,c)=>T.texParameterf(a,b,c),Vd:function(a,b,c){T.texParameterf(a,b,y[c>>>0>>>2>>>0])},Ud:(a,b,
c)=>T.texParameteri(a,b,c),Td:function(a,b,c){T.texParameteri(a,b,w[c>>>0>>>2>>>0])},eb:(a,b,c,d,e)=>T.texStorage2D(a,b,c,d,e),db:(a,b,c,d,e,h)=>T.texStorage3D(a,b,c,d,e,h),Sd:function(a,b,c,d,e,h,k,l,m){m>>>=0;2<=V.qf.version&&T.Hf?T.texSubImage2D(a,b,c,d,e,h,k,l,m):(m=m?Ec(l,k,e,h,m):null,T.texSubImage2D(a,b,c,d,e,h,k,l,m))},Zc:function(a,b,c,d,e,h,k,l,m,q,p){p>>>=0;if(T.Hf)T.texSubImage3D(a,b,c,d,e,h,k,l,m,q,p);else if(p){var v=Dc(q);T.texSubImage3D(a,b,c,d,e,h,k,l,m,q,v,p>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else T.texSubImage3D(a,
b,c,d,e,h,k,l,m,q,null)},rc:function(a,b,c,d){c>>>=0;a=V.tf[a];for(var e=[],h=0;h<b;h++)e.push(A(w[c+4*h>>>2>>>0]));T.transformFeedbackVaryings(a,e,d)},Rd:(a,b)=>{T.uniform1f(W(a),b)},Qd:function(a,b,c){c>>>=0;if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=y[c+4*e>>>2>>>0];else d=y.subarray(c>>>2>>>0,c+4*b>>>2>>>0);T.uniform1fv(W(a),d)},Pd:(a,b)=>{T.uniform1i(W(a),b)},Od:function(a,b,c){c>>>=0;if(288>=b)for(var d=Fc[b],e=0;e<b;++e)d[e]=w[c+4*e>>>2>>>0];else d=w.subarray(c>>>2>>>0,c+4*b>>>2>>>0);T.uniform1iv(W(a),
d)},fc:(a,b)=>{T.uniform1ui(W(a),b)},bc:function(a,b,c){c>>>=0;b&&T.uniform1uiv(W(a),x,c>>>2,b)},Nd:(a,b,c)=>{T.uniform2f(W(a),b,c)},Md:function(a,b,c){c>>>=0;if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=y[c+4*e>>>2>>>0],d[e+1]=y[c+(4*e+4)>>>2>>>0]}else d=y.subarray(c>>>2>>>0,c+8*b>>>2>>>0);T.uniform2fv(W(a),d)},Ld:(a,b,c)=>{T.uniform2i(W(a),b,c)},Kd:function(a,b,c){c>>>=0;if(144>=b){b*=2;for(var d=Fc[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>>2>>>0],d[e+1]=w[c+(4*e+4)>>>2>>>0]}else d=w.subarray(c>>>2>>>
0,c+8*b>>>2>>>0);T.uniform2iv(W(a),d)},ec:(a,b,c)=>{T.uniform2ui(W(a),b,c)},ac:function(a,b,c){c>>>=0;b&&T.uniform2uiv(W(a),x,c>>>2,2*b)},Jd:(a,b,c,d)=>{T.uniform3f(W(a),b,c,d)},Id:function(a,b,c){c>>>=0;if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=y[c+4*e>>>2>>>0],d[e+1]=y[c+(4*e+4)>>>2>>>0],d[e+2]=y[c+(4*e+8)>>>2>>>0]}else d=y.subarray(c>>>2>>>0,c+12*b>>>2>>>0);T.uniform3fv(W(a),d)},Hd:(a,b,c,d)=>{T.uniform3i(W(a),b,c,d)},Gd:function(a,b,c){c>>>=0;if(96>=b){b*=3;for(var d=Fc[b],e=0;e<b;e+=3)d[e]=
w[c+4*e>>>2>>>0],d[e+1]=w[c+(4*e+4)>>>2>>>0],d[e+2]=w[c+(4*e+8)>>>2>>>0]}else d=w.subarray(c>>>2>>>0,c+12*b>>>2>>>0);T.uniform3iv(W(a),d)},dc:(a,b,c,d)=>{T.uniform3ui(W(a),b,c,d)},$b:function(a,b,c){c>>>=0;b&&T.uniform3uiv(W(a),x,c>>>2,3*b)},Fd:(a,b,c,d,e)=>{T.uniform4f(W(a),b,c,d,e)},Ed:function(a,b,c){c>>>=0;if(72>=b){var d=X[4*b],e=y;c>>>=2;b*=4;for(var h=0;h<b;h+=4){var k=c+h;d[h]=e[k>>>0];d[h+1]=e[k+1>>>0];d[h+2]=e[k+2>>>0];d[h+3]=e[k+3>>>0]}}else d=y.subarray(c>>>2>>>0,c+16*b>>>2>>>0);T.uniform4fv(W(a),
d)},Dd:(a,b,c,d,e)=>{T.uniform4i(W(a),b,c,d,e)},Cd:function(a,b,c){c>>>=0;if(72>=b){b*=4;for(var d=Fc[b],e=0;e<b;e+=4)d[e]=w[c+4*e>>>2>>>0],d[e+1]=w[c+(4*e+4)>>>2>>>0],d[e+2]=w[c+(4*e+8)>>>2>>>0],d[e+3]=w[c+(4*e+12)>>>2>>>0]}else d=w.subarray(c>>>2>>>0,c+16*b>>>2>>>0);T.uniform4iv(W(a),d)},cc:(a,b,c,d,e)=>{T.uniform4ui(W(a),b,c,d,e)},_b:function(a,b,c){c>>>=0;b&&T.uniform4uiv(W(a),x,c>>>2,4*b)},Nb:(a,b,c)=>{a=V.tf[a];T.uniformBlockBinding(a,b,c)},Bd:function(a,b,c,d){d>>>=0;if(72>=b){b*=4;for(var e=
X[b],h=0;h<b;h+=4)e[h]=y[d+4*h>>>2>>>0],e[h+1]=y[d+(4*h+4)>>>2>>>0],e[h+2]=y[d+(4*h+8)>>>2>>>0],e[h+3]=y[d+(4*h+12)>>>2>>>0]}else e=y.subarray(d>>>2>>>0,d+16*b>>>2>>>0);T.uniformMatrix2fv(W(a),!!c,e)},Lc:function(a,b,c,d){d>>>=0;b&&T.uniformMatrix2x3fv(W(a),!!c,y,d>>>2,6*b)},Jc:function(a,b,c,d){d>>>=0;b&&T.uniformMatrix2x4fv(W(a),!!c,y,d>>>2,8*b)},Ad:function(a,b,c,d){d>>>=0;if(32>=b){b*=9;for(var e=X[b],h=0;h<b;h+=9)e[h]=y[d+4*h>>>2>>>0],e[h+1]=y[d+(4*h+4)>>>2>>>0],e[h+2]=y[d+(4*h+8)>>>2>>>0],e[h+
3]=y[d+(4*h+12)>>>2>>>0],e[h+4]=y[d+(4*h+16)>>>2>>>0],e[h+5]=y[d+(4*h+20)>>>2>>>0],e[h+6]=y[d+(4*h+24)>>>2>>>0],e[h+7]=y[d+(4*h+28)>>>2>>>0],e[h+8]=y[d+(4*h+32)>>>2>>>0]}else e=y.subarray(d>>>2>>>0,d+36*b>>>2>>>0);T.uniformMatrix3fv(W(a),!!c,e)},Kc:function(a,b,c,d){d>>>=0;b&&T.uniformMatrix3x2fv(W(a),!!c,y,d>>>2,6*b)},Hc:function(a,b,c,d){d>>>=0;b&&T.uniformMatrix3x4fv(W(a),!!c,y,d>>>2,12*b)},zd:function(a,b,c,d){d>>>=0;if(18>=b){var e=X[16*b],h=y;d>>>=2;b*=16;for(var k=0;k<b;k+=16){var l=d+k;e[k]=
h[l>>>0];e[k+1]=h[l+1>>>0];e[k+2]=h[l+2>>>0];e[k+3]=h[l+3>>>0];e[k+4]=h[l+4>>>0];e[k+5]=h[l+5>>>0];e[k+6]=h[l+6>>>0];e[k+7]=h[l+7>>>0];e[k+8]=h[l+8>>>0];e[k+9]=h[l+9>>>0];e[k+10]=h[l+10>>>0];e[k+11]=h[l+11>>>0];e[k+12]=h[l+12>>>0];e[k+13]=h[l+13>>>0];e[k+14]=h[l+14>>>0];e[k+15]=h[l+15>>>0]}}else e=y.subarray(d>>>2>>>0,d+64*b>>>2>>>0);T.uniformMatrix4fv(W(a),!!c,e)},Ic:function(a,b,c,d){d>>>=0;b&&T.uniformMatrix4x2fv(W(a),!!c,y,d>>>2,8*b)},Gc:function(a,b,c,d){d>>>=0;b&&T.uniformMatrix4x3fv(W(a),!!c,
y,d>>>2,12*b)},Oc:a=>{if(!mc(a))return V.nf(1280),g("GL_INVALID_ENUM in glUnmapBuffer"),0;var b=V.mg[lc(a)];if(!b||!b.Pf)return V.nf(1282),g("buffer was never mapped in glUnmapBuffer"),0;b.Bg&16||T.bufferSubData(a,b.offset,r.subarray(b.Pf>>>0,b.Pf+b.length>>>0));O(b.Pf);b.Pf=0;return 1},yd:a=>{a=V.tf[a];T.useProgram(a);T.Xg=a},xd:a=>{T.validateProgram(V.tf[a])},wd:(a,b)=>T.vertexAttrib1f(a,b),vd:function(a,b){T.vertexAttrib1f(a,y[b>>>0>>>2])},ud:(a,b,c)=>T.vertexAttrib2f(a,b,c),td:function(a,b){b>>>=
0;T.vertexAttrib2f(a,y[b>>>2],y[b+4>>>2])},sd:(a,b,c,d)=>T.vertexAttrib3f(a,b,c,d),rd:function(a,b){b>>>=0;T.vertexAttrib3f(a,y[b>>>2],y[b+4>>>2],y[b+8>>>2])},qd:(a,b,c,d,e)=>T.vertexAttrib4f(a,b,c,d,e),pd:function(a,b){b>>>=0;T.vertexAttrib4f(a,y[b>>>2],y[b+4>>>2],y[b+8>>>2],y[b+12>>>2])},qb:Gc,ua:Gc,id:Gc,jd:Gc,bb:Gc,mc:(a,b,c,d,e)=>T.vertexAttribI4i(a,b,c,d,e),kc:function(a,b){b>>>=0;T.vertexAttribI4i(a,w[b>>>2],w[b+4>>>2],w[b+8>>>2],w[b+12>>>2])},lc:(a,b,c,d,e)=>T.vertexAttribI4ui(a,b,c,d,e),
jc:function(a,b){b>>>=0;T.vertexAttribI4ui(a,x[b>>>2],x[b+4>>>2],x[b+8>>>2],x[b+12>>>2])},pc:function(a,b,c,d,e){e>>>=0;var h=V.qf.Kf[a];T.$f?(h.Uf=!1,T.vertexAttribIPointer(a,b,c,d,e)):(h.size=b,h.type=c,h.wg=!1,h.stride=d,h.rf=e,h.Uf=!0,h.zg=function(k,l,m,q,p,v){this.vertexAttribIPointer(k,l,m,p,v)})},od:function(a,b,c,d,e,h){h>>>=0;var k=V.qf.Kf[a];T.$f?(k.Uf=!1,T.vertexAttribPointer(a,b,c,!!d,e,h)):(k.size=b,k.type=c,k.wg=d,k.stride=e,k.rf=h,k.Uf=!0,k.zg=function(l,m,q,p,v,z){this.vertexAttribPointer(l,
m,q,p,v,z)})},nd:(a,b,c,d)=>T.viewport(a,b,c,d),Gb:function(a,b,c){c=Number(c);T.waitSync(V.Qf[a>>>0],b,c)},Sa:function(a){a>>>=0;var b=r.length;if(4294901760<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(4294901760,65536*Math.ceil(Math.max(a,d)/65536))-ta.buffer.byteLength+65535)/65536|0;try{ta.grow(d);sa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},Pa:function(a,b){a>>>=0;b>>>=0;var c=0,d=0,e;for(e of Jc()){var h=b+c;x[a+d>>>2>>>0]=h;
c+=S(e,h,Infinity)+1;d+=4}return 0},Qa:function(a,b){a>>>=0;b>>>=0;var c=Jc();x[a>>>2>>>0]=c.length;a=0;for(var d of c)a+=Hb(d)+1;x[b>>>2>>>0]=a;return 0},l:a=>{la=a;Yb(a)},o:()=>52,Wa:function(){return 52},Ta:function(){return 70},Va:function(a,b,c,d){b>>>=0;c>>>=0;d>>>=0;for(var e=0,h=0;h<c;h++){var k=x[b>>>2>>>0],l=x[b+4>>>2>>>0];b+=8;for(var m=0;m<l;m++){var q=a,p=r[k+m>>>0],v=Kc[q];if(0===p||10===p){q=1===q?ia:g;p=0;p>>>=0;var z=Ja(v,p);p=Ia.decode(v.buffer?v.subarray(p,z):new Uint8Array(v.slice(p,
z)));q(p);v.length=0}else v.push(p)}e+=l}x[d>>>2>>>0]=e;return 0},La:Yb};function Uc(){var a=Z;a=Object.assign({},a);var b=c=>d=>c(d)>>>0;a.ef=b(a.ef);a.gf=b(a.gf);a.lf=b(a.lf);a.mf=(c=>()=>c()>>>0)(a.mf);return a}var Z;
Z=await (async function(){function a(c){Z=c.exports;c=Z=Uc();tb=c.ef;vc=c.gf;O=c.hf;Sc=c.jf;Nc=c.kf;Lc=c.lf;Mc=c.mf;ta=c.cf;pb=c.ff;sa();return Z}var b={a:Tc};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});va??=f.locateFile?f.locateFile?f.locateFile("libktx.wasm",ea):ea+"libktx.wasm":(new URL("libktx.wasm",import.meta.url)).href;return a((await ya(b)).instance)}());
(function(){function a(){f.calledRun=!0;if(!ka){ra=!0;Z.df();ma?.(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ba.push(b)}Aa(Ba)}}if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Da();Aa(Ca);f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()})();ra?moduleRtn=f:moduleRtn=new Promise((a,b)=>{ma=a;na=b});
;return moduleRtn}export default createKtxModule;
// -*- tab-width: 4; -*-
// vi: set sw=2 ts=4 expandtab textwidth=80:

//
// Copyright 2019-2024 Khronos Group, Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Provide old module create function name for backward compatibility.
// N.B. --pre-js and --post-js code is run inside the module creation
// function so the variable holding that function is not available.
// This has to be --extern-post-js.

var LIBKTX
if (typeof createKtxReadModule === "function")
  LIBKTX = createKtxReadModule;
else
  LIBKTX = createKtxModule;
