async function MSC_TRANSCODER(moduleArg={}){var moduleRtn;var l=moduleArg,aa=!!globalThis.WorkerGlobalScope,ba=import.meta.url,ca="",da,ea;if(globalThis.window||aa){try{ca=(new URL(".",ba)).href}catch{}aa&&(ea=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)});da=async b=>{b=await fetch(b,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}
var fa=console.log.bind(console),m=console.error.bind(console),q,u=!1,ha,ia,ja,w,x,A,C,D,E,F,ka,la,ma,na=!1;function oa(){var b=pa.buffer;l.HEAP8=w=new Int8Array(b);A=new Int16Array(b);l.HEAPU8=x=new Uint8Array(b);C=new Uint16Array(b);D=new Int32Array(b);E=new Uint32Array(b);F=new Float32Array(b);ka=new Float64Array(b);la=new BigInt64Array(b);ma=new BigUint64Array(b)}
function qa(b){l.onAbort?.(b);b="Aborted("+b+")";m(b);u=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");ja?.(b);throw b;}var ra;async function sa(b){if(!q)try{var a=await da(b);return new Uint8Array(a)}catch{}if(b==ra&&q)b=new Uint8Array(q);else if(ea)b=ea(b);else throw"both async and sync fetching of the wasm failed";return b}
async function ta(b,a){try{var c=await sa(b);return await WebAssembly.instantiate(c,a)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),qa(d)}}async function ua(b){var a=ra;if(!q)try{var c=fetch(a,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,b)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return ta(a,b)}
class va{name="ExitStatus";constructor(b){this.message=`Program terminated with exit(${b})`;this.status=b}}var wa=b=>{for(;0<b.length;)b.shift()(l)},xa=[],ya=[],za=()=>{var b=l.preRun.shift();ya.push(b)},Aa=!0;class Ba{constructor(b){this.W=b-24}}var Ca=0,Da=0,G=b=>{b>>>=0;for(var a="";;){var c=x[b++>>>0];if(!c)return a;a+=String.fromCharCode(c)}},H={},I={},Ea={},J=class extends Error{constructor(b){super(b);this.name="BindingError"}},Fa=b=>{throw new J(b);};
function Ga(b,a,c={}){var d=a.name;if(!b)throw new J(`type "${d}" must have a positive integer typeid pointer`);if(I.hasOwnProperty(b)){if(c.Ya)return;throw new J(`Cannot register type '${d}' twice`);}I[b]=a;delete Ea[b];H.hasOwnProperty(b)&&(a=H[b],delete H[b],a.forEach(e=>e()))}function L(b,a,c={}){return Ga(b,a,c)}
var Ha=(b,a,c)=>{switch(a){case 1:return c?d=>w[d>>>0]:d=>x[d>>>0];case 2:return c?d=>A[d>>>1>>>0]:d=>C[d>>>1>>>0];case 4:return c?d=>D[d>>>2>>>0]:d=>E[d>>>2>>>0];case 8:return c?d=>la[d>>>3>>>0]:d=>ma[d>>>3>>>0];default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},Ia=b=>{throw new J(b.U.Z.V.name+" instance already deleted");},Ja=!1,La=()=>{},M=b=>{if(!globalThis.FinalizationRegistry)return M=a=>a,b;Ja=new FinalizationRegistry(a=>{a=a.U;--a.count.value;0===a.count.value&&(a.aa?a.ea.ja(a.aa):
a.Z.V.ja(a.W))});M=a=>{var c=a.U;c.aa&&Ja.register(a,{U:c},a);return a};La=a=>{Ja.unregister(a)};return M(b)},Ma=[];function Na(){}
var Oa=(b,a)=>Object.defineProperty(a,"name",{value:b}),Pa={},Qa=(b,a,c)=>{if(void 0===b[a].$){var d=b[a];b[a]=function(...e){if(!b[a].$.hasOwnProperty(e.length))throw new J(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].$})!`);return b[a].$[e.length].apply(this,e)};b[a].$=[];b[a].$[d.la]=d}},Ra=(b,a,c)=>{if(l.hasOwnProperty(b)){if(void 0===c||void 0!==l[b].$&&void 0!==l[b].$[c])throw new J(`Cannot register public name '${b}' twice`);Qa(l,b,b);if(l[b].$.hasOwnProperty(c))throw new J(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
l[b].$[c]=a}else l[b]=a,l[b].la=c},Sa=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:b};function Ta(b,a,c,d,e,f,g,h){this.name=b;this.constructor=a;this.ia=c;this.ja=d;this.ca=e;this.Va=f;this.sa=g;this.Sa=h;this.fb=[]}
var Ua=(b,a,c)=>{for(;a!==c;){if(!a.sa)throw new J(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.sa(b);a=a.ca}return b},Va=b=>{if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b};
function Wa(b,a){if(null===a){if(this.za)throw new J(`null is not a valid ${this.name}`);return 0}if(!a.U)throw new J(`Cannot pass "${Va(a)}" as a ${this.name}`);if(!a.U.W)throw new J(`Cannot pass deleted object as a pointer of type ${this.name}`);return Ua(a.U.W,a.U.Z.V,this.V)}
function Xa(b,a){if(null===a){if(this.za)throw new J(`null is not a valid ${this.name}`);if(this.va){var c=this.gb();null!==b&&b.push(this.ja,c);return c}return 0}if(!a||!a.U)throw new J(`Cannot pass "${Va(a)}" as a ${this.name}`);if(!a.U.W)throw new J(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ua&&a.U.Z.ua)throw new J(`Cannot convert argument of type ${a.U.ea?a.U.ea.name:a.U.Z.name} to parameter type ${this.name}`);c=Ua(a.U.W,a.U.Z.V,this.V);if(this.va){if(void 0===
a.U.aa)throw new J("Passing raw pointer to smart pointer is illegal");switch(this.kb){case 0:if(a.U.ea===this)c=a.U.aa;else throw new J(`Cannot convert argument of type ${a.U.ea?a.U.ea.name:a.U.Z.name} to parameter type ${this.name}`);break;case 1:c=a.U.aa;break;case 2:if(a.U.ea===this)c=a.U.aa;else{var d=a.clone();c=this.hb(c,N(()=>d["delete"]()));null!==b&&b.push(this.ja,c)}break;default:throw new J("Unsupporting sharing policy");}}return c}
function Ya(b,a){if(null===a){if(this.za)throw new J(`null is not a valid ${this.name}`);return 0}if(!a.U)throw new J(`Cannot pass "${Va(a)}" as a ${this.name}`);if(!a.U.W)throw new J(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.U.Z.ua)throw new J(`Cannot convert argument of type ${a.U.Z.name} to parameter type ${this.name}`);return Ua(a.U.W,a.U.Z.V,this.V)}function Za(b){return this.Y(E[b>>>2>>>0])}
var $a=(b,a,c)=>{if(a===c)return b;if(void 0===c.ca)return null;b=$a(b,a,c.ca);return null===b?null:c.Sa(b)},ab={},bb=(b,a)=>{if(void 0===a)throw new J("ptr should not be undefined");for(;b.ca;)a=b.sa(a),b=b.ca;return ab[a]},cb=class extends Error{constructor(b){super(b);this.name="InternalError"}},db=(b,a)=>{if(!a.Z||!a.W)throw new cb("makeClassHandle requires ptr and ptrType");if(!!a.ea!==!!a.aa)throw new cb("Both smartPtrType and smartPtr must be specified");a.count={value:1};return M(Object.create(b,
{U:{value:a,writable:!0}}))};function eb(b,a,c,d,e,f,g,h,p,n,k){this.name=b;this.V=a;this.za=c;this.ua=d;this.va=e;this.eb=f;this.kb=g;this.Ja=h;this.gb=p;this.hb=n;this.ja=k;e||void 0!==a.ca?this.ba=Xa:(this.ba=d?Wa:Ya,this.da=null)}
var fb=(b,a,c)=>{if(!l.hasOwnProperty(b))throw new cb("Replacing nonexistent public symbol");void 0!==l[b].$&&void 0!==c?l[b].$[c]=a:(l[b]=a,l[b].la=c)},hb=(b,a,c=[])=>{a=gb.get(a)(...c);return"p"==b[0]?a>>>0:a},ib=(b,a)=>(...c)=>hb(b,a,c),O=(b,a)=>{b=G(b);var c=b.includes("p")?ib(b,a):gb.get(a);if("function"!=typeof c)throw new J(`unknown function pointer with signature ${b}: ${a}`);return c};class jb extends Error{}
var lb=b=>{b=kb(b);var a=G(b);R(b);return a},S=(b,a)=>{function c(f){e[f]||I[f]||(Ea[f]?Ea[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};a.forEach(c);throw new jb(`${b}: `+d.map(lb).join([", "]));},T=(b,a,c)=>{function d(h){h=c(h);if(h.length!==b.length)throw new cb("Mismatched type converter count");for(var p=0;p<b.length;++p)L(b[p],h[p])}b.forEach(h=>Ea[h]=a);var e=Array(a.length),f=[],g=0;a.forEach((h,p)=>{I.hasOwnProperty(h)?e[p]=I[h]:(f.push(h),H.hasOwnProperty(h)||(H[h]=[]),H[h].push(()=>
{e[p]=I[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},mb=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function nb(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].da)return!0;return!1}
function ob(b,a,c,d,e,f){var g=a.length;if(2>g)throw new J("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==a[1]&&null!==c,p=nb(a);c=!a[0].Fa;var n=a[0],k=a[1];d=[b,Fa,d,e,mb,n.Y.bind(n),k?.ba.bind(k)];for(e=2;e<g;++e)n=a[e],d.push(n.ba.bind(n));if(!p)for(e=h?1:2;e<a.length;++e)null!==a[e].da&&d.push(a[e].da);p=nb(a);e=a.length-2;k=[];n=["fn"];h&&n.push("thisWired");for(g=0;g<e;++g)k.push(`arg${g}`),n.push(`arg${g}Wired`);k=k.join(",");n=n.join(",");k=
`return function (${k}) {\n`;p&&(k+="var destructors = [];\n");var r=p?"destructors":"null",t="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(k+=`var thisWired = toClassParamWire(${r}, this);\n`);for(g=0;g<e;++g){var v=`toArg${g}Wire`;k+=`var arg${g}Wired = ${v}(${r}, arg${g});\n`;t.push(v)}k+=(c||f?"var rv = ":"")+`invoker(${n});\n`;if(p)k+="runDestructors(destructors);\n";else for(g=h?1:2;g<a.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",
null!==a[g].da&&(k+=`${f}_dtor(${f});\n`,t.push(`${f}_dtor`));c&&(k+="var ret = fromRetWire(rv);\nreturn ret;\n");a=(new Function(t,k+"}\n"))(...d);return Oa(b,a)}
var pb=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(E[a+4*d>>>2>>>0]);return c},qb=b=>{b=b.trim();const a=b.indexOf("(");return-1===a?b:b.slice(0,a)},sb=(b,a,c)=>{if(!(b instanceof Object))throw new J(`${c} with invalid "this": ${b}`);if(!(b instanceof a.V.constructor))throw new J(`${c} incompatible with "this" of type ${b.constructor.name}`);if(!b.U.W)throw new J(`cannot call emscripten binding method ${c} on deleted object`);return Ua(b.U.W,b.U.Z.V,a.V)},tb=[],U=[0,1,,1,null,1,!0,1,!1,1];
function ub(b){b>>>=0;9<b&&0===--U[b+1]&&(U[b]=void 0,tb.push(b))}
var V=b=>{if(!b)throw new J(`Cannot use deleted val. handle = ${b}`);return U[b]},N=b=>{switch(b){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const a=tb.pop()||U.length;U[a]=b;U[a+1]=1;return a}},vb={name:"emscripten::val",Y:b=>{var a=V(b);ub(b);return a},ba:(b,a)=>N(a),fa:Za,da:null},wb=(b,a,c)=>{switch(a){case 1:return c?function(d){return this.Y(w[d>>>0])}:function(d){return this.Y(x[d>>>0])};case 2:return c?function(d){return this.Y(A[d>>>1>>>0])}:function(d){return this.Y(C[d>>>
1>>>0])};case 4:return c?function(d){return this.Y(D[d>>>2>>>0])}:function(d){return this.Y(E[d>>>2>>>0])};default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},xb=(b,a)=>{var c=I[b];if(void 0===c)throw b=`${a} has unknown type ${lb(b)}`,new J(b);return c},yb=(b,a)=>{switch(a){case 4:return function(c){return this.Y(F[c>>>2>>>0])};case 8:return function(c){return this.Y(ka[c>>>3>>>0])};default:throw new TypeError(`invalid float width (${a}): ${b}`);}},zb=(b,a,c)=>{var d=x;a>>>=0;if(0<
c){c=a+c-1;for(var e=0;e<b.length;++e){var f=b.codePointAt(e);if(127>=f){if(a>=c)break;d[a++>>>0]=f}else if(2047>=f){if(a+1>=c)break;d[a++>>>0]=192|f>>6;d[a++>>>0]=128|f&63}else if(65535>=f){if(a+2>=c)break;d[a++>>>0]=224|f>>12;d[a++>>>0]=128|f>>6&63;d[a++>>>0]=128|f&63}else{if(a+3>=c)break;d[a++>>>0]=240|f>>18;d[a++>>>0]=128|f>>12&63;d[a++>>>0]=128|f>>6&63;d[a++>>>0]=128|f&63;e++}}d[a>>>0]=0}},Ab=b=>{for(var a=0,c=0;c<b.length;++c){var d=b.charCodeAt(c);127>=d?a++:2047>=d?a+=2:55296<=d&&57343>=d?
(a+=4,++c):a+=3}return a},Bb=new TextDecoder,Cb=(b,a,c,d)=>{c=a+c;if(d)return c;for(;b[a]&&!(a>=c);)++a;return a},Db=(b,a,c)=>(b>>>=0)?Bb.decode(x.subarray(b>>>0,Cb(x,b,a,c)>>>0)):"",Eb=new TextDecoder("utf-16le"),Fb=(b,a,c)=>{b>>>=1;return Eb.decode(C.subarray(b>>>0,Cb(C,b,a/2,c)>>>0))},Gb=(b,a,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)A[a>>>1>>>0]=b.charCodeAt(e),a+=2;A[a>>>1>>>0]=0;return a-d},Hb=b=>2*b.length,Ib=(b,a,c)=>{var d="";b>>>=2;
for(var e=0;!(e>=a/4);e++){var f=E[b+e>>>0];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Jb=(b,a,c)=>{a>>>=0;c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var f=b.codePointAt(e);65535<f&&e++;D[a>>>2>>>0]=f;a+=4;if(a+4>c)break}D[a>>>2>>>0]=0;return a-d},Kb=b=>{for(var a=0,c=0;c<b.length;++c)65535<b.codePointAt(c)&&c++,a+=4;return a},Lb=0,Mb=[],Nb=b=>{var a=Mb.length;Mb.push(b);return a},Ob=(b,a)=>{for(var c=Array(b),d=0;d<b;++d)c[d]=xb(E[a+4*d>>>2>>>0],`parameter ${d}`);
return c},Pb=(b,a,c)=>{var d=[];b=b(d,c);d.length&&(E[a>>>2>>>0]=N(d));return b},Qb={},Rb=b=>{var a=Qb[b];return void 0===a?G(b):a},W={},Sb=b=>{if(!(b instanceof va||"unwind"==b))throw b;},Tb=b=>{ha=b;Aa||0<Lb||(l.onExit?.(b),u=!0);throw new va(b);},Ub=b=>{if(!u)try{if(b(),!(Aa||0<Lb))try{ha=b=ha,Tb(b)}catch(a){Sb(a)}}catch(a){Sb(a)}},Vb=[null,[],[]],Zb=(b,a,c,d)=>{var e={string:n=>{var k=0;if(null!==n&&void 0!==n&&0!==n){k=Ab(n)+1;var r=Wb(k);zb(n,r,k);k=r}return k},array:n=>{var k=Wb(n.length);
w.set(n,k>>>0);return k}};b=l["_"+b];var f=[],g=0;if(d)for(var h=0;h<d.length;h++){var p=e[c[h]];p?(0===g&&(g=Xb()),f[h]=p(d[h])):f[h]=d[h]}c=b(...f);return c=function(n){0!==g&&Yb(g);return"string"===a?Db(n):"boolean"===a?!!n:n}(c)},X,$b=b=>{var a=b.getExtension("ANGLE_instanced_arrays");a&&(b.vertexAttribDivisor=(c,d)=>a.vertexAttribDivisorANGLE(c,d),b.drawArraysInstanced=(c,d,e,f)=>a.drawArraysInstancedANGLE(c,d,e,f),b.drawElementsInstanced=(c,d,e,f,g)=>a.drawElementsInstancedANGLE(c,d,e,f,g))},
ac=b=>{var a=b.getExtension("OES_vertex_array_object");a&&(b.createVertexArray=()=>a.createVertexArrayOES(),b.deleteVertexArray=c=>a.deleteVertexArrayOES(c),b.bindVertexArray=c=>a.bindVertexArrayOES(c),b.isVertexArray=c=>a.isVertexArrayOES(c))},bc=b=>{var a=b.getExtension("WEBGL_draw_buffers");a&&(b.drawBuffers=(c,d)=>a.drawBuffersWEBGL(c,d))},cc=b=>{var a="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(b.getSupportedExtensions()||[]).filter(c=>a.includes(c))},Y={counter:1,Ma:[],yb:{},Fb:[],tb:[],Ib:[],Ob:[],Kb:[],Ub:[],ha:[],Bb:{},Gb:[],Jb:[],Qb:[],Nb:[],Oa:5120,Na:[1,1,2,2,4,4,4,2,3,4,8],Lb:{},Mb:{},Rb:4,Sb:0,ib:b=>{Y.ab||(Y.ab=b)},Ea:b=>{for(var a=Y.counter++,c=b.length;c<a;c++)b[c]=null;for(;b[a];)a=Y.counter++;return a},ub:(b,a,c,d)=>{for(var e=0;e<b;e++){var f=X[c](),g=f&&Y.Ea(d);f?(f.name=g,d[g]=f):Y.ib(1282);D[a+4*e>>>2>>>0]=g}},ya:2097152,Ia:64,wa:b=>32-Math.clz32(0===b?0:b-1),Ua:(b,
a)=>{var c=Y.wa(Y.ya);a.ka=[];a.xa=[];a.ka.length=a.xa.length=c+1;a.oa=[];a.ra=[];a.oa.length=a.ra.length=c+1;a.na=[];a.na.length=c+1;for(var d=0;d<=c;++d){a.na[d]=null;a.ka[d]=a.xa[d]=0;var e=Y.Ia;a.oa[d]=[];a.ra[d]=[];var f=a.oa[d],g=a.ra[d];f.length=g.length=e;for(var h=0;h<e;++h)f[h]=g[h]=null}if(b){a.lb=X.createBuffer();a.ga.bindBuffer(34963,a.lb);b=Y.ya>>1;c=new Uint16Array(b);for(e=d=0;;){c[d++]=e;if(d>=b)break;c[d++]=e+1;if(d>=b)break;c[d++]=e+2;if(d>=b)break;c[d++]=e;if(d>=b)break;c[d++]=
e+2;if(d>=b)break;c[d++]=e+3;if(d>=b)break;e+=4}a.ga.bufferData(34963,c,35044);a.ga.bindBuffer(34963,null)}},Xa:b=>{b=Y.wa(b);var a=Y.X.oa[b],c=Y.X.ka[b];Y.X.ka[b]=Y.X.ka[b]+1&Y.Ia-1;var d=a[c];if(d)return d;d=X.getParameter(34964);a[c]=X.createBuffer();X.bindBuffer(34962,a[c]);X.bufferData(34962,1<<b,35048);X.bindBuffer(34962,d);return a[c]},wb:b=>{b=Y.wa(b);var a=Y.X.na[b];if(a)return a;a=X.getParameter(34965);Y.X.na[b]=X.createBuffer();X.bindBuffer(34963,Y.X.na[b]);X.bufferData(34963,1<<b,35048);
X.bindBuffer(34963,a);return Y.X.na[b]},bb:()=>{if(Y.X){var b=Y.X.oa;Y.X.oa=Y.X.ra;Y.X.ra=b;b=Y.X.ka;Y.X.ka=Y.X.xa;Y.X.xa=b;b=Y.wa(Y.ya);for(var a=0;a<=b;++a)Y.X.ka[a]=0}},vb:(b,a,c,d)=>{b="";for(var e=0;e<a;++e)b+=Db(E[c+4*e>>>2>>>0],d?E[d+4*e>>>2>>>0]:void 0);return b},Pa:(b,a,c,d)=>0<c?d*c:b*Y.Na[a-Y.Oa]*d,Tb:[],Db:b=>{Y.Ka=!1;for(var a=0;a<Y.X.Ha;++a){var c=Y.X.Ba[a];if(c.Qa&&c.enabled){Y.Ka=!0;var d=Y.Pa(c.size,c.type,c.stride,b),e=Y.Xa(d);X.bindBuffer(34962,e);X.bufferSubData(34962,0,x.subarray(c.W>>>
0,c.W+d>>>0));c.mb.call(X,a,c.size,c.type,c.cb,c.stride,0)}}},Cb:()=>{Y.Ka&&X.bindBuffer(34962,Y.Ma[X.ob])},nb:(b,a)=>{if(l.preinitializedWebGLContext){var c=l.preinitializedWebGLContext;a.Ga=Number(c.getParameter(c.VERSION).match(/^WebGL (\d+).\d+/)[1])}else b.Aa||(b.Aa=b.getContext,b.getContext=function(d,e){e=b.Aa(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null}),c=1<a.Ga?b.getContext("webgl2",a):b.getContext("webgl",a);return c?Y.jb(c,a):0},jb:(b,a)=>{var c=Y.Ea(Y.ha),d={handle:c,
attributes:a,version:a.Ga,ga:b};b.canvas&&(b.canvas.La=d);Y.ha[c]=d;("undefined"==typeof a.Ta||a.Ta)&&Y.Za(d);d.Ha=d.ga.getParameter(34921);d.Ba=[];for(b=0;b<d.Ha;b++)d.Ba[b]={enabled:!1,Qa:!1,size:0,type:0,cb:0,stride:0,W:0,mb:null};Y.Ua(!1,d);return c},xb:b=>{Y.X=Y.ha[b];l.ctx=X=Y.X?.ga;return!(b&&!X)},getContext:b=>Y.ha[b],pb:b=>{Y.X===Y.ha[b]&&(Y.X=null);"object"==typeof JSEvents&&JSEvents.Hb(Y.ha[b].ga.canvas);Y.ha[b]?.ga.canvas&&(Y.ha[b].ga.canvas.La=void 0);Y.ha[b]=null},Za:b=>{b||=Y.X;if(!b.$a){b.$a=
!0;var a=b.ga;a.Ab=a.getExtension("WEBGL_multi_draw");a.sb=a.getExtension("EXT_polygon_offset_clamp");a.rb=a.getExtension("EXT_clip_control");a.Vb=a.getExtension("WEBGL_polygon_mode");$b(a);ac(a);bc(a);a.qb=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");a.zb=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=b.version&&(a.Da=a.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>b.version||!a.Da)a.Da=a.getExtension("EXT_disjoint_timer_query");cc(a).forEach(c=>
{c.includes("lose_context")||c.includes("debug")||a.getExtension(c)})}}};
(()=>{let b=Na.prototype;Object.assign(b,{isAliasOf:function(c){if(!(this instanceof Na&&c instanceof Na))return!1;var d=this.U.Z.V,e=this.U.W;c.U=c.U;var f=c.U.Z.V;for(c=c.U.W;d.ca;)e=d.sa(e),d=d.ca;for(;f.ca;)c=f.sa(c),f=f.ca;return d===f&&e===c},clone:function(){this.U.W||Ia(this);if(this.U.qa)return this.U.count.value+=1,this;var c=M,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.U;c=c(e.call(d,f,{U:{value:{count:g.count,pa:g.pa,qa:g.qa,W:g.W,Z:g.Z,aa:g.aa,ea:g.ea}}}));c.U.count.value+=
1;c.U.pa=!1;return c},["delete"](){this.U.W||Ia(this);if(this.U.pa&&!this.U.qa)throw new J("Object already scheduled for deletion");La(this);var c=this.U;--c.count.value;0===c.count.value&&(c.aa?c.ea.ja(c.aa):c.Z.V.ja(c.W));this.U.qa||(this.U.aa=void 0,this.U.W=void 0)},isDeleted:function(){return!this.U.W},deleteLater:function(){this.U.W||Ia(this);if(this.U.pa&&!this.U.qa)throw new J("Object already scheduled for deletion");Ma.push(this);this.U.pa=!0;return this}});const a=Symbol.dispose;a&&(b[a]=
b["delete"])})();
Object.assign(eb.prototype,{Wa(b){this.Ja&&(b=this.Ja(b));return b},Ca(b){this.ja?.(b)},fa:Za,Y:function(b){function a(){return this.va?db(this.V.ia,{Z:this.eb,W:c,ea:this,aa:b}):db(this.V.ia,{Z:this,W:b})}var c=this.Wa(b);if(!c)return this.Ca(b),null;var d=bb(this.V,c);if(void 0!==d){if(0===d.U.count.value)return d.U.W=c,d.U.aa=b,d.clone();d=d.clone();this.Ca(b);return d}d=this.V.Va(c);d=Pa[d];if(!d)return a.call(this);d=this.ua?d.Ra:d.pointerType;var e=$a(c,this.V,d.V);return null===e?a.call(this):
this.va?db(d.V.ia,{Z:d,W:e,ea:this,aa:b}):db(d.V.ia,{Z:d,W:e})}});var dc=()=>Y.bb();"undefined"!=typeof MainLoop&&MainLoop.Eb.push(dc);l.noExitRuntime&&(Aa=l.noExitRuntime);l.print&&(fa=l.print);l.printErr&&(m=l.printErr);l.wasmBinary&&(q=l.wasmBinary);if(l.preInit)for("function"==typeof l.preInit&&(l.preInit=[l.preInit]);0<l.preInit.length;)l.preInit.shift()();l.ccall=Zb;l.cwrap=(b,a,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==a&&e&&!d?l["_"+b]:(...f)=>Zb(b,a,c,f,d)};
l.setValue=function(b,a,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":w[b>>>0]=a;break;case "i8":w[b>>>0]=a;break;case "i16":A[b>>>1>>>0]=a;break;case "i32":D[b>>>2>>>0]=a;break;case "i64":la[b>>>3>>>0]=BigInt(a);break;case "float":F[b>>>2>>>0]=a;break;case "double":ka[b>>>3>>>0]=a;break;case "*":E[b>>>2>>>0]=a;break;default:qa(`invalid type for setValue: ${c}`)}};
l.getValue=function(b,a="i8"){a.endsWith("*")&&(a="*");switch(a){case "i1":return w[b>>>0];case "i8":return w[b>>>0];case "i16":return A[b>>>1>>>0];case "i32":return D[b>>>2>>>0];case "i64":return la[b>>>3>>>0];case "float":return F[b>>>2>>>0];case "double":return ka[b>>>3>>>0];case "*":return E[b>>>2>>>0];default:qa(`invalid type for getValue: ${a}`)}};l.GL=Y;
var kb,R,ec,fc,Yb,Wb,Xb,pa,gb,gc={s:function(b,a,c){b>>>=0;var d=new Ba(b);E[d.W+16>>>2>>>0]=0;E[d.W+4>>>2>>>0]=a>>>0;E[d.W+8>>>2>>>0]=c>>>0;Ca=b;Da++;throw Ca;},A:()=>qa(""),o:function(b,a,c,d,e){b>>>=0;c>>>=0;a=G(a>>>0);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}L(b,{name:a,Y:f,ba:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},fa:Ha(a,c,!d),da:null})},I:function(b,a,c,d){a=G(a>>>0);L(b>>>0,{name:a,Y:function(e){return!!e},ba:function(e,f){return f?c:d},fa:function(e){return this.Y(x[e>>>
0])},da:null})},h:function(b,a,c,d,e,f,g,h,p,n,k,r,t){b>>>=0;a>>>=0;c>>>=0;d>>>=0;f>>>=0;g>>>=0;h>>>=0;p>>>=0;n>>>=0;k>>>=0;r>>>=0;t>>>=0;k=G(k);f=O(e>>>0,f);h&&=O(g,h);n&&=O(p,n);t=O(r,t);var v=Sa(k);Ra(v,function(){S(`Cannot construct ${k} due to unbound types`,[d])});T([b,a,c],d?[d]:[],y=>{y=y[0];if(d){var z=y.V;var P=z.ia}else P=Na.prototype;y=Oa(k,function(...Ka){if(Object.getPrototypeOf(this)!==Q)throw new J(`Use 'new' to construct ${k}`);if(void 0===B.ma)throw new J(`${k} has no accessible constructor`);
var rb=B.ma[Ka.length];if(void 0===rb)throw new J(`Tried to invoke ctor of ${k} with invalid number of parameters (${Ka.length}) - expected (${Object.keys(B.ma).toString()}) parameters instead!`);return rb.apply(this,Ka)});var Q=Object.create(P,{constructor:{value:y}});y.prototype=Q;var B=new Ta(k,y,Q,t,z,f,h,n);if(B.ca){var K;(K=B.ca).ta??(K.ta=[]);B.ca.ta.push(B)}z=new eb(k,B,!0,!1,!1);K=new eb(k+"*",B,!1,!1,!1);P=new eb(k+" const*",B,!1,!0,!1);Pa[b]={pointerType:K,Ra:P};fb(v,y);return[z,K,P]})},
l:function(b,a,c,d,e,f,g,h){b>>>=0;a>>>=0;e>>>=0;f>>>=0;g>>>=0;var p=pb(c,d>>>0);a=G(a);a=qb(a);f=O(e,f);T([],[b],n=>{function k(){S(`Cannot call ${r} due to unbound types`,p)}n=n[0];var r=`${n.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);var t=n.V.constructor;void 0===t[a]?(k.la=c-1,t[a]=k):(Qa(t,a,r),t[a].$[c-1]=k);T([],p,v=>{v=ob(r,[v[0],null].concat(v.slice(1)),null,f,g,h);void 0===t[a].$?(v.la=c-1,t[a]=v):t[a].$[c-1]=v;if(n.V.ta)for(const y of n.V.ta)y.constructor.hasOwnProperty(a)||
(y.constructor[a]=v);return[]});return[]})},i:function(b,a,c,d,e,f){b>>>=0;d>>>=0;e>>>=0;f>>>=0;var g=pb(a,c>>>0);e=O(d,e);T([],[b],h=>{h=h[0];var p=`constructor ${h.name}`;void 0===h.V.ma&&(h.V.ma=[]);if(void 0!==h.V.ma[a-1])throw new J(`Cannot register multiple constructors with identical number of parameters (${a-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.V.ma[a-1]=()=>{S(`Cannot construct ${h.name} due to unbound types`,
g)};T([],g,n=>{n.splice(1,0,null);h.V.ma[a-1]=ob(p,n,null,e,f);return[]});return[]})},g:function(b,a,c,d,e,f,g,h,p){b>>>=0;a>>>=0;e>>>=0;f>>>=0;g>>>=0;var n=pb(c,d>>>0);a=G(a);a=qb(a);f=O(e,f);T([],[b],k=>{function r(){S(`Cannot call ${t} due to unbound types`,n)}k=k[0];var t=`${k.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);h&&k.V.fb.push(a);var v=k.V.ia,y=v[a];void 0===y||void 0===y.$&&y.className!==k.name&&y.la===c-2?(r.la=c-2,r.className=k.name,v[a]=r):(Qa(v,a,t),v[a].$[c-2]=r);
T([],n,z=>{z=ob(t,z,k,f,g,p);void 0===v[a].$?(z.la=c-2,v[a]=z):v[a].$[c-2]=z;return[]});return[]})},c:function(b,a,c,d,e,f,g,h,p,n){b>>>=0;a>>>=0;c>>>=0;e>>>=0;f>>>=0;g>>>=0;h>>>=0;p>>>=0;n>>>=0;a=G(a);e=O(d>>>0,e);T([],[b],k=>{k=k[0];var r=`${k.name}.${a}`,t={get(){S(`Cannot access ${r} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};t.set=p?()=>S(`Cannot access ${r} due to unbound types`,[c,g]):()=>{throw new J(r+" is a read-only property");};Object.defineProperty(k.V.ia,a,t);T([],
p?[c,g]:[c],v=>{var y=v[0],z={get(){var Q=sb(this,k,r+" getter");return y.Y(e(f,Q))},enumerable:!0};if(p){p=O(h,p);var P=v[1];z.set=function(Q){var B=sb(this,k,r+" setter"),K=[];p(n,B,P.ba(K,Q));mb(K)}}Object.defineProperty(k.V.ia,a,z);return[]});return[]})},G:function(b){return L(b>>>0,vb)},j:function(b,a,c,d){function e(){}a=G(a>>>0);e.values={};L(b>>>0,{name:a,constructor:e,Y:function(f){return this.constructor.values[f]},ba:(f,g)=>g.value,fa:wb(a,c>>>0,d),da:null});Ra(a,e)},a:function(b,a,c){a>>>=
0;var d=xb(b>>>0,"enum");a=G(a);b=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Oa(`${d.name}_${a}`,function(){})}});b.values[c]=d;b[a]=d},n:function(b,a,c){a=G(a>>>0);L(b>>>0,{name:a,Y:d=>d,ba:(d,e)=>e,fa:yb(a,c>>>0),da:null})},m:function(b,a,c,d,e,f,g){b>>>=0;d>>>=0;e>>>=0;f>>>=0;var h=pb(a,c>>>0);b=G(b);b=qb(b);e=O(d,e);Ra(b,function(){S(`Cannot call ${b} due to unbound types`,h)},a-1);T([],h,p=>{fb(b,ob(b,[p[0],null].concat(p.slice(1)),null,e,f,g),a-
1);return[]})},d:function(b,a,c,d,e){b>>>=0;c>>>=0;a=G(a>>>0);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}L(b,{name:a,Y:f,ba:(h,p)=>p,fa:Ha(a,c,0!==d),da:null})},b:function(b,a,c){function d(f){return new e(w.buffer,E[f+4>>>2>>>0],E[f>>>2>>>0])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][a];c=G(c>>>0);L(b>>>0,{name:c,Y:d,fa:d},{Ya:!0})},H:function(b,a){a=G(a>>>0);L(b>>>0,{name:a,Y(c){var d=Db(c+4,E[c>>>
2>>>0],!0);R(c);return d},ba(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new J("Cannot pass non-string to std::string");var f=e?Ab(d):d.length;var g=ec(4+f+1),h=g+4;E[g>>>2>>>0]=f;e?zb(d,h,f+1):x.set(d,h>>>0);null!==c&&c.push(R,g);return g},fa:Za,da(c){R(c)}})},k:function(b,a,c){a>>>=0;c>>>=0;c=G(c);if(2===a){var d=Fb;var e=Gb;var f=Hb}else d=Ib,e=Jb,f=Kb;L(b>>>0,{name:c,Y:g=>{var h=d(g+4,E[g>>>2>>>0]*a,
!0);R(g);return h},ba:(g,h)=>{if("string"!=typeof h)throw new J(`Cannot pass non-string to C++ string type ${c}`);var p=f(h),n=ec(4+p+a);E[n>>>2>>>0]=p/a;e(h,n+4,p+a);null!==g&&g.push(R,n);return n},fa:Za,da(g){R(g)}})},J:function(b,a){a=G(a>>>0);L(b>>>0,{Fa:!0,name:a,Y:()=>{},ba:()=>{}})},u:()=>{Aa=!1;Lb=0},f:function(b,a,c){var [d,...e]=Ob(b,a>>>0);a=d.ba.bind(d);var f=e.map(p=>p.fa.bind(p));b--;var g={toValue:V};b=f.map((p,n)=>{var k=`argFromPtr${n}`;g[k]=p;return`${k}(args${n?"+"+8*n:""})`});
switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=Rb,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${b})`;d.Fa||(g.toReturnWire=a,g.emval_returnValue=Pb,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(p=>p.name)}) => ${d.name}>`;return Nb(Oa(h,
c))},r:ub,E:function(b){b=Rb(b>>>0);return N(l[b])},F:function(b,a){a>>>=0;b=V(b>>>0);a=V(a);return N(b[a])},q:function(b){b>>>=0;9<b&&(U[b+1]+=1)},e:function(b,a,c,d,e){return Mb[b>>>0](a>>>0,c>>>0,d>>>0,e>>>0)},D:function(b){return N(Rb(b>>>0))},C:function(){return N({})},p:function(b){b>>>=0;var a=V(b);mb(a);ub(b)},B:function(b,a,c){a>>>=0;c>>>=0;b=V(b>>>0);a=V(a);c=V(c);b[a]=c},v:(b,a)=>{W[b]&&(clearTimeout(W[b].id),delete W[b]);if(!a)return 0;var c=setTimeout(()=>{delete W[b];Ub(()=>fc(b,performance.now()))},
a);W[b]={id:c,Pb:a};return 0},w:function(b){b>>>=0;var a=x.length;if(4294901760<b)return!1;for(var c=1;4>=c;c*=2){var d=a*(1+.2/c);d=Math.min(d,b+100663296);a:{d=(Math.min(4294901760,65536*Math.ceil(Math.max(b,d)/65536))-pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);oa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},z:()=>52,x:function(){return 70},y:function(b,a,c,d){a>>>=0;c>>>=0;d>>>=0;for(var e=0,f=0;f<c;f++){var g=E[a>>>2>>>0],h=E[a+4>>>2>>>0];a+=8;for(var p=0;p<h;p++){var n=
b,k=x[g+p>>>0],r=Vb[n];if(0===k||10===k){n=1===n?fa:m;k=0;k>>>=0;var t=Cb(r,k);k=Bb.decode(r.buffer?r.subarray(k,t):new Uint8Array(r.slice(k,t)));n(k);r.length=0}else r.push(k)}e+=h}E[d>>>2>>>0]=e;return 0},t:Tb};function hc(){var b=Z;b=Object.assign({},b);var a=c=>d=>c(d)>>>0;b.M=a(b.M);b.P=a(b.P);b.S=a(b.S);b.T=(c=>()=>c()>>>0)(b.T);return b}var Z;
Z=await (async function(){function b(c){Z=c.exports;c=Z=hc();kb=c.M;R=c.O;ec=c.P;fc=c.Q;Yb=c.R;Wb=c.S;Xb=c.T;pa=c.K;gb=c.N;oa();return Z}var a={a:gc};if(l.instantiateWasm)return new Promise(c=>{l.instantiateWasm(a,(d,e)=>{c(b(d,e))})});ra??=l.locateFile?l.locateFile?l.locateFile("msc_basis_transcoder.wasm",ca):ca+"msc_basis_transcoder.wasm":(new URL("msc_basis_transcoder.wasm",import.meta.url)).href;return b((await ua(a)).instance)}());
(function(){function b(){l.calledRun=!0;if(!u){na=!0;Z.L();ia?.(l);l.onRuntimeInitialized?.();if(l.postRun)for("function"==typeof l.postRun&&(l.postRun=[l.postRun]);l.postRun.length;){var a=l.postRun.shift();xa.push(a)}wa(xa)}}if(l.preRun)for("function"==typeof l.preRun&&(l.preRun=[l.preRun]);l.preRun.length;)za();wa(ya);l.setStatus?(l.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>l.setStatus(""),1);b()},1)):b()})();na?moduleRtn=l:moduleRtn=new Promise((b,a)=>{ia=b;ja=a});
;return moduleRtn}export default MSC_TRANSCODER;
