#! /bin/bash

# Smudge driver for the kwexpander filter for expanding keywords. Currently
# only $Date$ is supported.
#
# Add something like
#    [filter "kwexpander"]
#	smudge = $(git rev-parse --show-toplevel)/expandkw %f
#	clean = sed -e 's/\\$Date.*\\$/$Date$/'
# to .git/config.

last_date=$(git log --pretty=format:"%ad" -1 HEAD -- "$1")
sed -e 's/\$Date.*\$/$Date: '"$last_date \$"/
