#! /bin/bash
# -*- tab-width: 4; -*-
# vi: set sw=2 ts=4:

# Regenerate the input ktx files for libktx tests.

# Copyright 2025 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

# Depth of this script relative to the project root
depth=../..

# Change dir to the resources/input folder, the script location...
cd $(dirname $0)

function usage() {
  echo "Usage: $0 [--tooldir,-t <path/to/dir/with/ktx>] [--cubemaps,-c] [--icons,-i]"
  exit $1
}

function check_exec() {
  if [ -z "$1" -o ! -x "$1" ]; then
    if [ $2 -eq 1 ]; then
      echo "$0: $1 not found."
      exit 1
    else
      echo $3
    fi
  fi
}

function check_path() {
  if which $1 >/dev/null; then
    #declare -g $1="$1"  # For recent versions of bash.
    eval "$1=\$1"
  else
    echo "$1 not found in $PATH."
    exit 1
  fi
}

gen_cubemaps=0
gen_ktxicons=0

while [ $# -ne 0 ]; do
  case $1 in
    --tooldir | -t)
      if [ $# -ge 1 ]; then
        ktx=$2/ktx
        check_exec $ktx 1
      else
        usage 1
      fi
      shift 2 ;;
    --cubemaps | -c)
      gen_cubemaps=1
      shift ;;
    --icons | -i)
      gen_ktxicons=1
      shift ;;
    *) usage 1 ;;
  esac
done

if [ -z "$ktx" ]; then
  check_path ktx
fi

testktx="$ktx --testrun"
#$testktx

# For threadtests
$ktx create --testrun --format R8G8B8A8_SRGB --levels 7 input/npbm/level0-alpha.pam input/npbm/level1-alpha.pam input/npbm/level2-alpha.pam input/npbm/level3-alpha.pam input/npbm/level4-alpha.pam input/npbm/level5-alpha.pam input/npbm/level6-alpha.pam ktx2/rgba_mipmap.ktx2
$ktx create --testrun --format R8G8B8A8_SRGB --encode basis-lz --levels 7 input/npbm/level0-alpha.pam input/npbm/level1-alpha.pam input/npbm/level2-alpha.pam input/npbm/level3-alpha.pam input/npbm/level4-alpha.pam input/npbm/level5-alpha.pam input/npbm/level6-alpha.pam ktx2/rgba_mipmap_basis.ktx2
$ktx transcode --testrun --target etc-rgba ktx2/rgba_mipmap_basis.ktx2 ktx2/rgba_mipmap_etc2.ktx2
$ktx create --testrun --format ASTC_4x4_SRGB_BLOCK --levels 7 input/npbm/level0-alpha.pam input/npbm/level1-alpha.pam input/npbm/level2-alpha.pam input/npbm/level3-alpha.pam input/npbm/level4-alpha.pam input/npbm/level5-alpha.pam input/npbm/level6-alpha.pam ktx2/rgba_mipmap_astc.ktx2

# For texturetests
for i in نَسِيج テクスチャ 质地 조직 hűtő
do
  $ktx create --testrun --format R8G8B8A8_SRGB --assign-tf srgb input/png/テクスチャ.png unicode/$i.ktx2
  $ktx create --testrun --format R8G8B8A8_SRGB --assign-tf srgb --zstd 5 input/png/テクスチャ.png unicode/${i}_zstd.ktx2
done

# For transcodetests and loadtests. For transcode tests some .basis files
# are also needed. See genbasis.
$ktx create --testrun --format R8G8B8A8_SRGB --assign-tf srgb --encode basis-lz input/png/alpha_simple.png ktx2/alpha_simple_basis.ktx2
$ktx create --testrun --format R8G8B8_SRGB --encode basis-lz input/png/kodim17.png ktx2/kodim17_basis.ktx2
$ktx create --testrun --format R8G8B8A8_SRGB --assign-tf srgb --encode basis-lz input/png/color_grid.png ktx2/color_grid_basis.ktx2

# For loadtests. Optional, because they take a while, especially if using
# the Debug config.
if [ $gen_cubemaps -ne 0 ]; then
  $ktx create --testrun --format R8G8B8_SRGB --encode basis-lz --cubemap --generate-mipmap  @@input/jpg/Yokohama3/filelist.txt ktx2/cubemap_yokohama_basis_rd.ktx2
  $ktx create --testrun --format R8G8B8_SRGB --encode uastc --cubemap --scale 0.5 --generate-mipmap --uastc-rdo --uastc-rdo-l 4 --zstd 5 @@input/jpg/GoldenGateBridge3/filelist.txt ktx2/cubemap_goldengate_uastc_rdo4_zstd5_rd.ktx2
fi

# For loadtests. Optional, because they expect a particular arrangement of
# cloned KTX-Software and KTX-Specification repos.
if [ $gen_ktxicons -ne 0 ]; then
  ktxspec_dir=$depth/../KTX-Specification
  webgl_read_test_dir=../webgl/libktx-read-webgl
  $ktx create --testrun --format R8G8B8A8_SRGB --generate-mipmap --encode basis-lz --scale 0.5 $ktxspec_dir/icons/png/ktx_app.png $webgl_read_test_dir/ktx_app_basis.ktx2
  $ktx create --testrun --format R8G8B8A8_SRGB --encode uastc --uastc-rdo --uastc-rdo-l 5.0 --width 1000 --height 1392 $ktxspec_dir/icons/png/ktx_document.png $webgl_read_test_dir/ktx_document_uastc_rdo5.ktx2
  $ktx create --testrun --format R8G8B8A8_SRGB --generate-mipmap --encode basis-lz $ktxspec_dir/icons/png/ktx_document.png ktx2/ktx_document_basis.ktx2
  # threads 1 here is to avoid non-determism in the RDO processing.
  # Hopefully a fix will be forthcoming.
  $ktx create --testrun --format R8G8B8A8_SRGB --generate-mipmap --threads 1 --encode uastc --uastc-rdo --uastc-rdo-l 4 --zstd 5 $ktxspec_dir/icons/png/ktx_document.png ktx2/ktx_document_uastc_rdo4_zstd5.ktx2
fi

# For loadtests.
$ktx create --testrun --format R8G8B8A8_SRGB --convert-tf srgb --depth 7 input/png/red16.png input/png/orange16.png input/png/yellow16.png input/png/green16.png input/png/blue16.png input/png/indigo16.png input/png/violet16.png ktx2/3dtex_7_reference_u.ktx2
$ktx create --testrun --format R8G8B8A8_SRGB --convert-tf srgb --layers 7 --generate-mipmap input/png/red16.png input/png/orange16.png input/png/yellow16.png input/png/green16.png input/png/blue16.png input/png/indigo16.png input/png/violet16.png ktx2/arraytex_7_mipmap_reference_u.ktx2
$ktx create --testrun --format R8G8B8A8_SRGB --assign-tf srgb --encode uastc input/png/color_grid.png ktx2/color_grid_uastc.ktx2
$ktx create --testrun --format R8G8B8A8_SRGB --assign-tf srgb --encode uastc --zstd 5 input/png/color_grid.png ktx2/color_grid_uastc_zstd.ktx2
$ktx create --testrun --format R8G8B8A8_SRGB --assign-tf srgb --zstd 5 input/png/color_grid.png ktx2/color_grid_zstd.ktx2
$ktx create --testrun --format R8G8B8_SRGB --assign-tf srgb --encode basis-lz input/png/FlightHelmet_baseColor.png ktx2/FlightHelmet_baseColor_basis.ktx2
$ktx create --testrun  --format R8G8B8_UNORM --no-warn-on-color-conversions --assign-tf linear --generate-mipmap  --normalize --normal-mode --encode basis-lz input/jpg/Iron_Bars/Iron_Bars_001_normal_unnormalized.png ktx2/etc1s_Iron_Bars_001_normal.ktx2
$ktx create --testrun --format R8G8B8_UNORM --no-warn-on-color-conversions --assign-tf linear --generate-mipmap --normalize --normal-mode --encode uastc --zstd 5  input/jpg/Iron_Bars/Iron_Bars_001_normal_unnormalized.png ktx2/uastc_Iron_Bars_001_normal.ktx2
$ktx create --testrun --format R8G8B8A8_SRGB --convert-texcoord-origin bottom-left input/npbm/up.ppm ktx2/orient_up_metadata_u.ktx2
$ktx create --testrun --format R8G8B8A8_SRGB --convert-texcoord-origin top-left input/npbm/up.ppm ktx2/orient_down_metadata_u.ktx2

$ktx convert --testrun -t ktx ktx/pattern_02_bc2.ktx ktx2/pattern_02_bc2.ktx2
#$ktx convert --testrun -t ktx ktx/rgba-reference.ktx ktx2/rgba-reference-u.ktx
$ktx convert --testrun -t ktx ktx/texturearray_astc_8x8_unorm.ktx ktx2/texturearray_astc_8x8_unorm.ktx2
$ktx convert --testrun -t ktx ktx/texturearray_bc3_unorm.ktx ktx2/texturearray_bc3_unorm.ktx2
$ktx convert --testrun -t ktx ktx/texturearray_etc2_unorm.ktx ktx2/texturearray_etc2_unorm.ktx2

# No sources for premultiplied-rgba.ktx2, straight-rgba.ktx2 or skybox_zstd.ktx2.

#$toktx --lower_left_maps_to_s0t0 --nometadata rgb-reference.ktx ../srcimages/rgb.ppm
## The purpose of this is testing automatic mipmap generation. Since SRGB is
## not color renderable on ES3 or WebGL, therefore AMG won't work, use linear.
#$toktx --automipmap --lower_left_maps_to_s0t0 --nometadata --linear rgb-amg-reference.ktx ../srcimages/rgb.ppm
#$toktx --lower_left_maps_to_s0t0 --nometadata orient-up.ktx ../srcimages/up.ppm
#$toktx --lower_left_maps_to_s0t0 orient-up-metadata.ktx ../srcimages/up.ppm
#$toktx orient-down-metadata.ktx ../srcimages/up.ppm
#$toktx --lower_left_maps_to_s0t0 --mipmap --nometadata rgb-mipmap-reference.ktx ../srcimages/level0.ppm ../srcimages/level1.ppm ../srcimages/level2.ppm ../srcimages/level3.ppm ../srcimages/level4.ppm ../srcimages/level5.ppm ../srcimages/level6.ppm
#$toktx --lower_left_maps_to_s0t0 --nometadata rgba-reference.ktx ../srcimages/rgba.pam
#$toktx --uastc --genmipmap --test cimg5293_uastc.ktx2 ../srcimages/CIMG5293.jpg
#$toktx --zcmp --uastc --genmipmap --test cimg5293_uastc_zstd.ktx2 ../srcimages/CIMG5293.jpg
#$toktx --nowarn --bcmp --test camera_camera_BaseColor_basis.ktx2 ../srcimages/camera_camera_BaseColor_16bit.png
#$toktx --nowarn --uastc 1 --test camera_camera_BaseColor_uastc.ktx2 ../srcimages/camera_camera_BaseColor_16bit.png
#$toktx --nowarn --bcmp --test CesiumLogoFlat.ktx2 ../srcimages/CesiumLogoFlat_palette.png
#$toktx --nowarn --t2 --test tbrn2c08.ktx2 ../srcimages/tbrn2c08.png
#$toktx --nowarn --t2 --test tbyn3p08.ktx2 ../srcimages/tbyn3p08.png
#$toktx --nowarn --t2 --test tm3n3p02.ktx2 ../srcimages/tm3n3p02.png
#$toktx --nowarn --t2 --test --convert_oetf linear luminance_reference_u.ktx2 ../srcimages/luminance.pgm
#$toktx --nowarn --t2 --test --uastc -- luminance_reference_uastc.ktx2 ../srcimages/luminance.pgm
#$toktx --nowarn --t2 --test --bcmp luminance_reference_basis.ktx2 ../srcimages/luminance.pgm
#$toktx --nowarn --t2 --test luminance_alpha_reference_u.ktx2 ../srcimages/basn4a08.png
#$toktx --nowarn --t2 --test --uastc -- luminance_alpha_reference_uastc.ktx2 ../srcimages/basn4a08.png
#$toktx --nowarn --t2 --test --bcmp luminance_alpha_reference_basis.ktx2 ../srcimages/basn4a08.png
#$toktx --nowarn --t2 --test --convert_oetf linear --target_type R r_reference_u.ktx2 ../srcimages/luminance.pgm
#$toktx --nowarn --t2 --test --target_type R --swizzle r001 --uastc -- r_reference_uastc.ktx2 ../srcimages/luminance.pgm
#$toktx --nowarn --t2 --test --target_type R --swizzle r001 --bcmp r_reference_basis.ktx2 ../srcimages/luminance.pgm
#$toktx --nowarn --t2 --test --target_type RG rg_reference_u.ktx2 ../srcimages/basn4a08.png
#$toktx --nowarn --t2 --test --target_type RG --swizzle rg01 --uastc -- rg_reference_uastc.ktx2 ../srcimages/basn4a08.png
#$toktx --nowarn --t2 --test --target_type RG --swizzle ra01 --bcmp rg_reference_basis.ktx2 ../srcimages/basn4a08.png
## Input to the following is a red RGB texture.
#$toktx --nowarn --t2 --test --input_swizzle 0r01 green_rgb_reference_u.ktx2 ../srcimages/level0.ppm
#$toktx --nowarn --t2 --test --input_swizzle 0rr1 --target_type RGBA cyan_rgba_reference_u.ktx2 ../srcimages/level0.ppm
## BasisU encoders notice that alpha is all 1 and removes it, hence RGB output for these.
#$toktx --nowarn --t2 --test --input_swizzle 0rr1 --target_type RGBA --bcmp cyan_rgb_reference_basis.ktx2 ../srcimages/level0.ppm
#$toktx --nowarn --t2 --test --input_swizzle 0rr1 --target_type RGBA --uastc -- cyan_rgb_reference_uastc.ktx2 ../srcimages/level0.ppm
#
## ... and additional files for the load tests.
#
#$toktx --lower_left_maps_to_s0t0 rgb-reference-metadata.ktx ../srcimages/rgb.ppm
#
## generate astc reference images
#
#$toktx --test --encode astc --astc_blk_d 6x6 --genmipmap --cubemap astc_mipmap_ldr_cubemap_6x6.ktx2 ../srcimages/Yokohama3/posx.jpg ../srcimages/Yokohama3/negx.jpg ../srcimages/Yokohama3/posy.jpg ../srcimages/Yokohama3/negy.jpg ../srcimages/Yokohama3/posz.jpg ../srcimages/Yokohama3/negz.jpg
#$toktx --test --encode astc --astc_blk_d 6x6 --cubemap   astc_ldr_cubemap_6x6.ktx2 ../srcimages/Yokohama3/posx.jpg ../srcimages/Yokohama3/negx.jpg ../srcimages/Yokohama3/posy.jpg ../srcimages/Yokohama3/negy.jpg ../srcimages/Yokohama3/posz.jpg ../srcimages/Yokohama3/negz.jpg
#$toktx --test --encode astc --astc_blk_d 6x6 --genmipmap astc_mipmap_ldr_6x6_posx.ktx2 ../srcimages/Yokohama3/posx.jpg
#$toktx --test --encode astc --astc_blk_d 6x6             astc_ldr_6x6_posx.ktx2        ../srcimages/Yokohama3/posx.jpg
#$toktx --test --encode astc --astc_blk_d 6x6 --genmipmap astc_mipmap_ldr_6x6_posz.ktx2 ../srcimages/Yokohama3/posz.jpg
#$toktx --test --encode astc --astc_blk_d 6x6 --genmipmap astc_mipmap_ldr_6x6_posy.ktx2 ../srcimages/Yokohama3/posy.jpg
#
#$toktx --test --encode astc --astc_blk_d 6x6 --genmipmap --astc_quality fastest    astc_mipmap_ldr_6x6_kodim17_fastest.ktx2    ../srcimages/kodim17.png
#$toktx --test --encode astc --astc_blk_d 6x6 --genmipmap --astc_quality fast       astc_mipmap_ldr_6x6_kodim17_fast.ktx2       ../srcimages/kodim17.png
#$toktx --test --encode astc --astc_blk_d 6x6 --genmipmap --astc_quality medium     astc_mipmap_ldr_6x6_kodim17_medium.ktx2     ../srcimages/kodim17.png
#
#$toktx --test --encode astc --astc_blk_d 4x4    --genmipmap astc_mipmap_ldr_4x4_posx.ktx2   ../srcimages/Yokohama3/posx.jpg
#$toktx --test --encode astc --astc_blk_d 6x5    --genmipmap astc_mipmap_ldr_6x5_posx.ktx2   ../srcimages/Yokohama3/posx.jpg
#$toktx --test --encode astc --astc_blk_d 8x6    --genmipmap astc_mipmap_ldr_8x6_posx.ktx2   ../srcimages/Yokohama3/posx.jpg
#$toktx --test --encode astc --astc_blk_d 10x5   --genmipmap astc_mipmap_ldr_10x5_posx.ktx2  ../srcimages/Yokohama3/posx.jpg
#$toktx --test --encode astc --astc_blk_d 8x8    --genmipmap astc_mipmap_ldr_8x8_posx.ktx2   ../srcimages/Yokohama3/posx.jpg
#$toktx --test --encode astc --astc_blk_d 12x10  --genmipmap astc_mipmap_ldr_12x10_posx.ktx2 ../srcimages/Yokohama3/posx.jpg
#$toktx --test --encode astc --astc_blk_d 12x12  --genmipmap astc_mipmap_ldr_12x12_posx.ktx2 ../srcimages/Yokohama3/posx.jpg
#
#$toktx --test --encode astc --astc_blk_d 4x4    astc_ldr_4x4_FlightHelmet_baseColor.ktx2   ../srcimages/FlightHelmet_baseColor.png
#$toktx --test --encode astc --astc_blk_d 6x5    astc_ldr_6x5_FlightHelmet_baseColor.ktx2   ../srcimages/FlightHelmet_baseColor.png
#$toktx --test --encode astc --astc_blk_d 8x6    astc_ldr_8x6_FlightHelmet_baseColor.ktx2   ../srcimages/FlightHelmet_baseColor.png
#$toktx --test --encode astc --astc_blk_d 10x5   astc_ldr_10x5_FlightHelmet_baseColor.ktx2  ../srcimages/FlightHelmet_baseColor.png
#$toktx --test --encode astc --astc_blk_d 8x8    astc_ldr_8x8_FlightHelmet_baseColor.ktx2   ../srcimages/FlightHelmet_baseColor.png
#$toktx --test --encode astc --astc_blk_d 12x10  astc_ldr_12x10_FlightHelmet_baseColor.ktx2 ../srcimages/FlightHelmet_baseColor.png
#$toktx --test --encode astc --astc_blk_d 12x12  astc_ldr_12x12_FlightHelmet_baseColor.ktx2 ../srcimages/FlightHelmet_baseColor.png
#$toktx --test --assign_oetf linear --normalize --normal_mode --encode astc --astc_blk_d 6x6  astc_ldr_6x6_Iron_Bars_001_normal.ktx2 ../srcimages/Iron_Bars/Iron_Bars_001_normal_unnormalized.png
#$toktx --test --assign_oetf linear --normalize --normal_mode --encode astc --astc_blk_d 5x4  astc_ldr_5x4_Iron_Bars_001_normal.ktx2 ../srcimages/Iron_Bars/Iron_Bars_001_normal_unnormalized.png
#
#$toktx --test --layers 7 --encode astc --astc_blk_d 6x6             astc_ldr_6x6_arraytex_7.ktx2        ../srcimages/red16.png ../srcimages/orange16.png ../srcimages/yellow16.png ../srcimages/green16.png ../srcimages/blue16.png ../srcimages/indigo16.png ../srcimages/violet16.png
#$toktx --test --layers 7 --encode astc --astc_blk_d 6x6 --genmipmap astc_ldr_6x6_arraytex_7_mipmap.ktx2 ../srcimages/red16.png ../srcimages/orange16.png ../srcimages/yellow16.png ../srcimages/green16.png ../srcimages/blue16.png ../srcimages/indigo16.png ../srcimages/violet16.png
#$toktx --test --depth 7  --encode astc --astc_blk_d 6x6             astc_ldr_6x6_3dtex_7.ktx2           ../srcimages/red16.png ../srcimages/orange16.png ../srcimages/yellow16.png ../srcimages/green16.png ../srcimages/blue16.png ../srcimages/indigo16.png ../srcimages/violet16.png
#
#$toktx --test --layers 1 --t2 arraytex_1_reference_u.ktx2 ../srcimages/red16.png
#$toktx --test --depth 1 --t2 3dtex_1_reference_u.ktx2 ../srcimages/red16.png
#$toktx --test --depth 7 --t2 3dtex_7_reference_u.ktx2 ../srcimages/red16.png ../srcimages/orange16.png ../srcimages/yellow16.png ../srcimages/green16.png ../srcimages/blue16.png ../srcimages/indigo16.png ../srcimages/violet16.png
#$toktx --test --layers 7 --t2 arraytex_7_reference_u.ktx2 ../srcimages/red16.png ../srcimages/orange16.png ../srcimages/yellow16.png ../srcimages/green16.png ../srcimages/blue16.png ../srcimages/indigo16.png ../srcimages/violet16.png
#$toktx --test --depth 7 --t2 3dtex_7_reference_u.ktx2 ../srcimages/red16.png ../srcimages/orange16.png ../srcimages/yellow16.png ../srcimages/green16.png ../srcimages/blue16.png ../srcimages/indigo16.png ../srcimages/violet16.png
#$toktx --test --layers 7 --genmipmap --t2 arraytex_7_mipmap_reference_u.ktx2 ../srcimages/red16.png ../srcimages/orange16.png ../srcimages/yellow16.png ../srcimages/green16.png ../srcimages/blue16.png ../srcimages/indigo16.png ../srcimages/violet16.png
#
#$ktxsc -o skybox_zstd.ktx2 --force --test --zcmp 5 skybox.ktx2
#
#for name in hűtő نَسِيج テクスチャ 质地 조직; do
#  $toktx --test $name.ktx ../srcimages/$name.png
#  $ktx2ktx2 --test --force -o $name.ktx2 $name.ktx
#  $ktxsc --test -o ${name}_zstd.ktx2 --force --zcmp 5 $name.ktx2
#done
