#! /usr/bin/env bash
# -*- tab-width: 4; -*-
# vi: set sw=2 ts=4:

# Show ktxinfo output differences between files.

# Copyright 2017 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

for i in $*
do
  bad=$i
  ref=${i#toktx.}
  infobad=`mktemp $bad.XXXXXX.info` || exit 1
  inforef=`mktemp $ref.XXXXXX.info` || exit 1
  ktxinfo $ref > $inforef
  ktxinfo $bad > $infobad
  echo  "************ $bad ****************"
  diff $inforef $infobad
  rm $inforef $infobad
done
