#!/bin/sh

# Copyright 2023 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

# Build vulkan_core.h to be included with dfdutils. It is the standard
# vulkan_core.h with the unreleased VK_EXT_texture_compression_ASTC_3d
# extension force included and VK_KHR_video_decode_h264 and
# VK_KHR_video_decode_h265 removed due to their including other large
# header files.

# To use
#   1. Install Docker
#   2. In a terminal
#      $ cp build_custom_vulkan_core <your clone of the GitLab vulkan repo>
#      $ cd <your clone of the GitLab vulkan repo>
#      $ scripts/runDocker
#   3. At the prompt in the shell started by Docker
#      $ build_custom_vulkan_core
#      $ ^d
#   4. Back at the prompt in no. 2
#      $ mv vulkan_core.h <path to your dfdutils repo clone/vulkan/
#      $ rm build_custom_vulkan_core
#      $ cd <path to your dfdutils repo>
# The multiple copying steps are needed because programs cannot reach
# outside docker to the host file system.

scripts/genvk.py -extension VK_EXT_extension_289 -removeExtensions '(VK_KHR_video_decode_h264|VK_KHR_video_decode_h265)' -registry xml/vk.xml -o . vulkan_core.h
