# Copyright 2015-2020 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0
name: Check Determinism of Encoder Results Across Plaforms and Compilers

# The purpose of this is to show whether the encoding results are
# deterministic across platforms and compilers. It does this by building
# the library and tools then running the CTS with an option set that
# requires an exact match and won't use ktxdiff.
#
# The test is run across macOS, Ubuntu and Windows on both arm64 and x86_64
# processors using ktx and libktx compiled with clang and gcc. They are,
# in addition, compiled with AppleClang on macOS and with ClangCL and msvc
# on Windows.

on:
  workflow_dispatch:

# macOS runners: clang 17, clang 18 available on $(brew --prefix llvm@18)/bin/clang  & gcc-{13,14,15}
# Linux runners: clang 16, 17, 18 & gcc-{12,13,14}
# Windows runners: 
jobs:
  check-determinism:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, macos-15-intel, ubuntu-latest, ubuntu-24.04-arm, windows-2022, windows-11-arm ]
        compiler:
          - [ clang, clang++ ]
          - [ gcc, g++ ]
        config: [ Release ]
        generator: [ 'Ninja Multi-Config' ]
        exclude:
          - os: macos-latest
            compiler: [ gcc, g++ ] # Here gcc is an alias for clang
          - os: macos-15-intel
            compiler: [ gcc, g++ ] # ditto
        include:
          - os: macos-latest
            compiler: [ gcc-15, g++-15 ]
            config: Release
            generator: 'Ninja Multi-Config'
          - os: macos-latest
            compiler: [ $(brew --prefix llvm@18)/bin/clang, $(brew --prefix llvm@18)/bin/clang++ ]
            config: Release
            generator: 'Ninja Multi-Config'
          - os: macos-15-intel
            compiler: [ gcc-15, g++-15 ]
            config: Release
            generator: 'Ninja Multi-Config'
          - os: macos-15-intel
            compiler: [ $(brew --prefix llvm@18)/bin/clang, $(brew --prefix llvm@18)/bin/clang++ ]
            config: Release
            generator: 'Ninja Multi-Config'
          - os: windows-2022
            config: Release
            generator: 'Visual Studio 17 2022'
            toolset: v143
          - os: windows-2022
            config: Release
            generator: 'Visual Studio 17 2022'
            toolset: CLangCL
          - os: windows-11-arm
            config: Release
            generator: 'Visual Studio 17 2022'
            toolset: v143
          - os: windows-11-arm
            config: Release
            generator: 'Visual Studio 17 2022'
            toolset: CLangCL

    runs-on: ${{ matrix.os }}
    env:
      GIT_LFS_SKIP_SMUDGE: 1
      BUILD_DIR: build
      STANDARD_OPTIONS: '-D KTX_WERROR=OFF -D LIBKTX_VERSION_READ_ONLY=OFF -D KTX_FEATURE_TOOLS=ON -D KTX_FEATURE_TOOLS_CTS=ON -D KTX_TOOLS_CTS_PRIMARY_PLATFORM=ON -D KTX_FEATURE_TESTS=ON'

    steps:
    - uses: actions/checkout@v6
      with:
        # Fetch all history to make sure tags are
        # included (used for version creation)
        fetch-depth: 0
        # For the CTS submodule.
        submodules: true

    - name: Set macOS astcenc ISA override for x86_64
      if: matrix.os == 'macos-15-intel'
      run: echo ISA_OVERRIDE='-D ASTCENC_ISA_SSE41=ON' >> $GITHUB_ENV

    - name: Configure KTX software build for all but Visual Studio
      # Without the ${{ }}, this line generates a YAML syntax error. Do not understand why.
      if: ${{ !startsWith(matrix.generator, 'Visual Studio') }}
      run: cmake -B ${{ env.BUILD_DIR }} -G "${{ matrix.generator }}" -D CMAKE_C_COMPILER=${{ matrix.compiler[0] }} -D CMAKE_CXX_COMPILER=${{ matrix.compiler[1] }} ${{ env.STANDARD_OPTIONS }} ${{ env.ISA_OVERRIDE }}

    - name: Configure KTX software build for Visual Studio build
      if: startsWith(matrix.generator, 'Visual Studio')
      run: cmake -B ${{ env.BUILD_DIR }} -G "${{ matrix.generator }}" -T ${{ matrix.toolset }} ${{ env.STANDARD_OPTIONS }}

    - name: Build KTX software
      run: cmake --build ${{ env.BUILD_DIR }} --config=${{ matrix.config }} --target=ktxtools

    - name: Run KTX tools CTS
      run: ctest --output-on-failure --test-dir ${{ env.BUILD_DIR }} -C Release -R ktxToolsTest

